// API endpoint: GET/POST /api/automated-protocol-optimization/feedback
// Story 9.3: Automated protocol optimization - Protocol feedback management
// Generated by: VoidBeast V4.0

import type { NextRequest } from "next/server";

const service = new AutomatedProtocolOptimizationService();

// GET: List protocol feedback with optional filters
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);

    const filters = {
      protocol_id: searchParams.get("protocol_id") || undefined,
      provider_id: searchParams.get("provider_id") || undefined,
      feedback_type: searchParams.get("feedback_type") || undefined,
      status: searchParams.get("status") || undefined,
      priority_level: searchParams.get("priority_level") || undefined,
      page: parseInt(searchParams.get("page") || "1"),
      per_page: parseInt(searchParams.get("per_page") || "20"),
    };

    const result = await service.getProtocolFeedback(filters);

    return NextResponse.json({
      success: true,
      data: result.data,
      pagination: {
        page: filters.page,
        per_page: filters.per_page,
        total: result.total,
        total_pages: Math.ceil(result.total / filters.per_page),
      },
    });
  } catch (error) {
    console.error("Error fetching protocol feedback:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to fetch protocol feedback",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}

// POST: Create new protocol feedback
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    // Validate request data
    const validation = createProtocolFeedbackSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        {
          success: false,
          error: "Validation failed",
          details: validation.error.format(),
        },
        { status: 400 },
      );
    }

    const protocolFeedback = await service.createProtocolFeedback(validation.data);

    return NextResponse.json(
      {
        success: true,
        data: protocolFeedback,
        message: "Protocol feedback submitted successfully",
      },
      { status: 201 },
    );
  } catch (error) {
    console.error("Error creating protocol feedback:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to submit protocol feedback",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}
