// This file is auto-generated by Supabase CLI
// Run: npm run db:types to regenerate
// Database types for NeonPro healthcare platform

export interface Database {
  public: {
    Tables: {
      clinics: {
        Row: {
          id: string;
          name: string;
          slug: string;
          timezone: string;
          language: string;
          currency: string;
          created_at: string;
          updated_at: string;
          settings: Record<string, any> | null;
          lgpd_consent_date: string | null;
          anvisa_registration: string | null;
          professional_council_number: string | null;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          timezone?: string;
          language?: string;
          currency?: string;
          created_at?: string;
          updated_at?: string;
          settings?: Record<string, any> | null;
          lgpd_consent_date?: string | null;
          anvisa_registration?: string | null;
          professional_council_number?: string | null;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          timezone?: string;
          language?: string;
          currency?: string;
          created_at?: string;
          updated_at?: string;
          settings?: Record<string, any> | null;
          lgpd_consent_date?: string | null;
          anvisa_registration?: string | null;
          professional_council_number?: string | null;
          is_active?: boolean;
        };
      };
      users: {
        Row: {
          id: string;
          email: string;
          name: string;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
          professional_license: string | null;
          specialization: string[] | null;
          lgpd_consent_date: string | null;
          phone_number: string | null;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          email: string;
          name: string;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
          professional_license?: string | null;
          specialization?: string[] | null;
          lgpd_consent_date?: string | null;
          phone_number?: string | null;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
          professional_license?: string | null;
          specialization?: string[] | null;
          lgpd_consent_date?: string | null;
          phone_number?: string | null;
          is_active?: boolean;
        };
      };
      user_clinics: {
        Row: {
          user_id: string;
          clinic_id: string;
          role: 'admin' | 'professional' | 'staff' | 'receptionist';
          permissions: string[] | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          clinic_id: string;
          role: 'admin' | 'professional' | 'staff' | 'receptionist';
          permissions?: string[] | null;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          clinic_id?: string;
          role?: 'admin' | 'professional' | 'staff' | 'receptionist';
          permissions?: string[] | null;
          created_at?: string;
        };
      };
      appointments: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          professional_id: string;
          status: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
          start_time: string;
          end_time: string;
          service_type: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          version: number;
          lgpd_processing_consent: boolean;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          professional_id: string;
          status?: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
          start_time: string;
          end_time: string;
          service_type: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          version?: number;
          lgpd_processing_consent?: boolean;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          professional_id?: string;
          status?: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
          start_time?: string;
          end_time?: string;
          service_type?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          version?: number;
          lgpd_processing_consent?: boolean;
        };
      };
      leads: {
        Row: {
          id: string;
          clinic_id: string;
          name: string;
          email: string | null;
          phone: string | null;
          source: string;
          status: 'new' | 'contacted' | 'qualified' | 'converted' | 'lost';
          assigned_to: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          next_follow_up: string | null;
          ai_predictions: Record<string, any> | null;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          source?: string;
          status?: 'new' | 'contacted' | 'qualified' | 'converted' | 'lost';
          assigned_to?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          next_follow_up?: string | null;
          ai_predictions?: Record<string, any> | null;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          name?: string;
          email?: string | null;
          phone?: string | null;
          source?: string;
          status?: 'new' | 'contacted' | 'qualified' | 'converted' | 'lost';
          assigned_to?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          next_follow_up?: string | null;
          ai_predictions?: Record<string, any> | null;
        };
      };
      messages: {
        Row: {
          id: string;
          clinic_id: string;
          sender_id: string;
          recipient_id: string | null;
          appointment_id: string | null;
          lead_id: string | null;
          content: string;
          type: 'text' | 'system' | 'appointment_update' | 'lead_update';
          metadata: Record<string, any> | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          sender_id: string;
          recipient_id?: string | null;
          appointment_id?: string | null;
          lead_id?: string | null;
          content: string;
          type?: 'text' | 'system' | 'appointment_update' | 'lead_update';
          metadata?: Record<string, any> | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          sender_id?: string;
          recipient_id?: string | null;
          appointment_id?: string | null;
          lead_id?: string | null;
          content?: string;
          type?: 'text' | 'system' | 'appointment_update' | 'lead_update';
          metadata?: Record<string, any> | null;
          read_at?: string | null;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          first_name: string | null;
          last_name: string | null;
          display_name: string | null;
          phone: string | null;
          profession: 'medico' | 'enfermeiro' | 'fisioterapeuta' | 'nutricionista' | 'psicologo' | 'dentista' | 'admin' | 'recepcionista' | null;
          license: string | null;
          clinic_id: string | null;
          lgpd_consent: Record<string, any>;
          data_retention: Record<string, any>;
          preferences: Record<string, any>;
          created_at: string;
          updated_at: string;
          last_login_at: string | null;
          email_verified: boolean;
          phone_verified: boolean;
          two_factor_enabled: boolean;
        };
        Insert: {
          id?: string;
          first_name?: string | null;
          last_name?: string | null;
          display_name?: string | null;
          phone?: string | null;
          profession?: 'medico' | 'enfermeiro' | 'fisioterapeuta' | 'nutricionista' | 'psicologo' | 'dentista' | 'admin' | 'recepcionista' | null;
          license?: string | null;
          clinic_id?: string | null;
          lgpd_consent?: Record<string, any>;
          data_retention?: Record<string, any>;
          preferences?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
          email_verified?: boolean;
          phone_verified?: boolean;
          two_factor_enabled?: boolean;
        };
        Update: {
          id?: string;
          first_name?: string | null;
          last_name?: string | null;
          display_name?: string | null;
          phone?: string | null;
          profession?: 'medico' | 'enfermeiro' | 'fisioterapeuta' | 'nutricionista' | 'psicologo' | 'dentista' | 'admin' | 'recepcionista' | null;
          license?: string | null;
          clinic_id?: string | null;
          lgpd_consent?: Record<string, any>;
          data_retention?: Record<string, any>;
          preferences?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
          email_verified?: boolean;
          phone_verified?: boolean;
          two_factor_enabled?: boolean;
        };
      };
      service_types: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          duration_minutes: number;
          price: number;
          category: string;
          is_active: boolean;
          requires_appointment: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          duration_minutes?: number;
          price?: number;
          category?: string;
          is_active?: boolean;
          requires_appointment?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          duration_minutes?: number;
          price?: number;
          category?: string;
          is_active?: boolean;
          requires_appointment?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      professional_services: {
        Row: {
          id: string;
          professional_id: string;
          service_id: string;
          is_primary: boolean;
          proficiency_level: string;
          hourly_rate: number | null;
          is_active: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          professional_id: string;
          service_id: string;
          is_primary?: boolean;
          proficiency_level?: string;
          hourly_rate?: number | null;
          is_active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          professional_id?: string;
          service_id?: string;
          is_primary?: boolean;
          proficiency_level?: string;
          hourly_rate?: number | null;
          is_active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      user_profiles: {
        Row: {
          id: string;
          email: string;
          name: string;
          avatar_url: string | null;
          user_created_at: string;
          user_updated_at: string;
          first_name: string | null;
          last_name: string | null;
          display_name: string | null;
          phone: string | null;
          profession: 'medico' | 'enfermeiro' | 'fisioterapeuta' | 'nutricionista' | 'psicologo' | 'dentista' | 'admin' | 'recepcionista' | null;
          license: string | null;
          clinic_id: string | null;
          lgpd_consent: Record<string, any>;
          preferences: Record<string, any>;
          profile_created_at: string;
          profile_updated_at: string;
          last_login_at: string | null;
          email_verified: boolean;
          phone_verified: boolean;
          two_factor_enabled: boolean;
          clinic_roles: ('admin' | 'professional' | 'staff' | 'receptionist')[] | null;
        };
      };
    };
  };
}

// Type utilities for common operations
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T];
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
export type TablesRow<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];

export type Views<T extends keyof Database['public']['Views']> = Database['public']['Views'][T];
export type ViewsRow<T extends keyof Database['public']['Views']> = Database['public']['Views'][T]['Row'];