// Auto-generated Supabase types
// This file will be generated by: supabase gen types typescript

export type Database = {
  public: {
    Tables: {
      clinics: {
        Row: {
          id: string;
          name: string;
          owner_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          owner_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          owner_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      patients: {
        Row: {
          id: string;
          clinic_id: string;
          medical_record_number: string;
          full_name: string;
          cpf: string | null;
          birth_date: string | null;
          phone_primary: string | null;
          email: string | null;
          lgpd_consent_given: boolean;
          lgpd_consent_date: string | null;
          data_retention_until: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          medical_record_number: string;
          full_name: string;
          cpf?: string | null;
          birth_date?: string | null;
          phone_primary?: string | null;
          email?: string | null;
          lgpd_consent_given?: boolean;
          lgpd_consent_date?: string | null;
          data_retention_until?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          medical_record_number?: string;
          full_name?: string;
          cpf?: string | null;
          birth_date?: string | null;
          phone_primary?: string | null;
          email?: string | null;
          lgpd_consent_given?: boolean;
          lgpd_consent_date?: string | null;
          data_retention_until?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {
      appointment_status: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
      consent_status: 'pending' | 'granted' | 'withdrawn' | 'expired';
    };
  };
}