// Zod validation schemas for Automated Protocol Optimization System
// Story 9.3: Automated protocol optimization with continuous improvement
// Generated by: VoidBeast V4.0

import { z } from 'zod';

// Base validation schemas for enums and common patterns
const ApprovalStatusSchema = z.enum([
  'draft',
  'pending',
  'approved',
  'rejected',
  'deprecated',
]);
const FeedbackTypeSchema = z.enum([
  'improvement',
  'issue',
  'suggestion',
  'rating',
  'complaint',
]);
const PriorityLevelSchema = z.enum(['low', 'medium', 'high', 'critical']);
const FeedbackStatusSchema = z.enum([
  'open',
  'reviewed',
  'implemented',
  'rejected',
]);
const ExperimentTypeSchema = z.enum(['ab_test', 'multivariate', 'sequential']);
const ExperimentStatusSchema = z.enum([
  'setup',
  'running',
  'paused',
  'completed',
  'cancelled',
]);
const EvidenceTypeSchema = z.enum([
  'literature',
  'guideline',
  'regulation',
  'study',
  'best_practice',
]);
const EvidenceLevelSchema = z.enum(['A', 'B', 'C', 'D', 'expert_opinion']);
const VerificationStatusSchema = z.enum([
  'current',
  'outdated',
  'conflicting',
  'superseded',
]);
const ComplianceStatusSchema = z.enum([
  'compliant',
  'partial',
  'non_compliant',
  'unknown',
]);
const ImplementationScopeSchema = z.enum([
  'clinic_wide',
  'department',
  'provider',
  'pilot',
]);
const RolloutStrategySchema = z.enum([
  'immediate',
  'gradual',
  'pilot',
  'scheduled',
]);
const ImplementationStatusSchema = z.enum([
  'planned',
  'in_progress',
  'completed',
  'failed',
  'rolled_back',
]);
const OptimizationStatusSchema = z.enum([
  'pending',
  'approved',
  'implemented',
  'rejected',
]);
const AnalyticsPeriodSchema = z.enum([
  'daily',
  'weekly',
  'monthly',
  'quarterly',
]);

// Core entity schemas
export const ProtocolVersionSchema = z.object({
  id: z.string().uuid(),
  protocol_name: z.string().min(1).max(255),
  version_number: z.string().min(1).max(50),
  description: z.string().optional(),
  optimization_data: z.record(z.any()).default({}),
  protocol_content: z.record(z.any()),
  approval_status: ApprovalStatusSchema.default('draft'),
  approved_by: z.string().uuid().optional(),
  effective_date: z.string().datetime().optional(),
  expiry_date: z.string().datetime().optional(),
  is_active: z.boolean().default(false),
  optimization_score: z.number().min(0).max(100).optional(),
  success_rate: z.number().min(0).max(100).optional(),
  created_by: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export const ProtocolOutcomeSchema = z.object({
  id: z.string().uuid(),
  protocol_version_id: z.string().uuid(),
  patient_id: z.string().uuid(),
  treatment_id: z.string().uuid().optional(),
  outcome_data: z.record(z.any()),
  success_score: z.number().min(0).max(100),
  improvement_percentage: z.number().min(-100).max(100).optional(),
  complications: z.array(z.record(z.any())).default([]),
  side_effects: z.array(z.record(z.any())).default([]),
  patient_satisfaction: z.number().min(1).max(10).optional(),
  follow_up_date: z.string().datetime().optional(),
  outcome_date: z.string().datetime(),
  recorded_by: z.string().uuid().optional(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export const ProtocolFeedbackSchema = z.object({
  id: z.string().uuid(),
  protocol_id: z.string().uuid(),
  provider_id: z.string().uuid(),
  feedback_type: FeedbackTypeSchema,
  feedback_data: z.record(z.any()),
  improvement_suggestions: z.string().optional(),
  rating: z.number().min(1).max(5).optional(),
  priority_level: PriorityLevelSchema.default('medium'),
  status: FeedbackStatusSchema.default('open'),
  reviewed_by: z.string().uuid().optional(),
  reviewed_at: z.string().datetime().optional(),
  implementation_notes: z.string().optional(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export const OptimizationResultSchema = z.object({
  id: z.string().uuid(),
  protocol_id: z.string().uuid(),
  optimization_type: z.string().min(1).max(100),
  improvement_metrics: z.record(z.any()),
  validation_data: z.record(z.any()).default({}),
  confidence_score: z.number().min(0).max(100).optional(),
  statistical_significance: z.number().min(0).max(1).optional(),
  recommendation_data: z.record(z.any()).default({}),
  implementation_status: OptimizationStatusSchema.default('pending'),
  automated_analysis: z.record(z.any()).default({}),
  human_review_required: z.boolean().default(true),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export const ProtocolExperimentSchema = z.object({
  id: z.string().uuid(),
  experiment_name: z.string().min(1).max(255),
  description: z.string().optional(),
  control_protocol_id: z.string().uuid().optional(),
  test_protocol_id: z.string().uuid().optional(),
  experiment_type: ExperimentTypeSchema.default('ab_test'),
  status: ExperimentStatusSchema.default('setup'),
  start_date: z.string().datetime().optional(),
  end_date: z.string().datetime().optional(),
  target_sample_size: z.number().int().min(1).default(100),
  current_sample_size: z.number().int().min(0).default(0),
  statistical_power: z.number().min(0).max(1).default(0.8),
  significance_level: z.number().min(0).max(1).default(0.05),
  primary_metric: z.string().max(100).optional(),
  secondary_metrics: z.array(z.string()).default([]),
  results_data: z.record(z.any()).default({}),
  conclusion: z.string().optional(),
  created_by: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export const ProtocolEvidenceSchema = z.object({
  id: z.string().uuid(),
  protocol_id: z.string().uuid(),
  evidence_type: EvidenceTypeSchema,
  source_reference: z.string().min(1),
  evidence_level: EvidenceLevelSchema.optional(),
  evidence_data: z.record(z.any()).default({}),
  relevance_score: z.number().min(0).max(100).optional(),
  last_verified: z.string().datetime(),
  verification_status: VerificationStatusSchema.default('current'),
  compliance_status: ComplianceStatusSchema.default('compliant'),
  notes: z.string().optional(),
  created_by: z.string().uuid().optional(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export const ProtocolImplementationSchema = z.object({
  id: z.string().uuid(),
  protocol_version_id: z.string().uuid(),
  implementation_scope: ImplementationScopeSchema,
  target_providers: z.array(z.string().uuid()).default([]),
  implementation_date: z.string().datetime().optional(),
  rollout_strategy: RolloutStrategySchema.default('immediate'),
  training_required: z.boolean().default(true),
  training_completion_rate: z.number().min(0).max(100).optional(),
  adherence_rate: z.number().min(0).max(100).optional(),
  implementation_notes: z.string().optional(),
  status: ImplementationStatusSchema.default('planned'),
  success_metrics: z.record(z.any()).default({}),
  rollback_reason: z.string().optional(),
  implemented_by: z.string().uuid().optional(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export const ProtocolAnalyticsSchema = z.object({
  id: z.string().uuid(),
  protocol_version_id: z.string().uuid(),
  analytics_period: AnalyticsPeriodSchema,
  period_start: z.string().datetime(),
  period_end: z.string().datetime(),
  usage_count: z.number().int().min(0).default(0),
  success_rate: z.number().min(0).max(100).optional(),
  average_outcome_score: z.number().min(0).max(100).optional(),
  patient_satisfaction: z.number().min(1).max(10).optional(),
  provider_satisfaction: z.number().min(1).max(10).optional(),
  cost_effectiveness: z.number().optional(),
  time_efficiency: z.number().min(0).max(100).optional(),
  complication_rate: z.number().min(0).max(100).optional(),
  readmission_rate: z.number().min(0).max(100).optional(),
  performance_metrics: z.record(z.any()).default({}),
  comparative_analysis: z.record(z.any()).default({}),
  roi_analysis: z.record(z.any()).default({}),
  trend_analysis: z.record(z.any()).default({}),
  calculated_at: z.string().datetime(),
  created_at: z.string().datetime(),
});

// Request validation schemas
export const CreateProtocolVersionRequestSchema = z.object({
  protocol_name: z.string().min(1).max(255),
  version_number: z.string().min(1).max(50),
  description: z.string().optional(),
  protocol_content: z.record(z.any()),
  optimization_data: z.record(z.any()).default({}),
});

export const UpdateProtocolVersionRequestSchema = z.object({
  protocol_name: z.string().min(1).max(255).optional(),
  description: z.string().optional(),
  protocol_content: z.record(z.any()).optional(),
  optimization_data: z.record(z.any()).optional(),
  approval_status: ApprovalStatusSchema.optional(),
  effective_date: z.string().datetime().optional(),
  expiry_date: z.string().datetime().optional(),
  is_active: z.boolean().optional(),
});

export const CreateProtocolOutcomeRequestSchema = z.object({
  protocol_version_id: z.string().uuid(),
  patient_id: z.string().uuid(),
  treatment_id: z.string().uuid().optional(),
  outcome_data: z.record(z.any()),
  success_score: z.number().min(0).max(100),
  improvement_percentage: z.number().min(-100).max(100).optional(),
  complications: z.array(z.record(z.any())).default([]),
  side_effects: z.array(z.record(z.any())).default([]),
  patient_satisfaction: z.number().min(1).max(10).optional(),
  follow_up_date: z.string().datetime().optional(),
  outcome_date: z.string().datetime(),
});

export const CreateProtocolFeedbackRequestSchema = z.object({
  protocol_id: z.string().uuid(),
  feedback_type: FeedbackTypeSchema,
  feedback_data: z.record(z.any()),
  improvement_suggestions: z.string().optional(),
  rating: z.number().min(1).max(5).optional(),
  priority_level: PriorityLevelSchema.default('medium'),
});

export const UpdateProtocolFeedbackRequestSchema = z.object({
  feedback_data: z.record(z.any()).optional(),
  improvement_suggestions: z.string().optional(),
  rating: z.number().min(1).max(5).optional(),
  priority_level: PriorityLevelSchema.optional(),
  status: FeedbackStatusSchema.optional(),
  implementation_notes: z.string().optional(),
});

export const CreateProtocolExperimentRequestSchema = z.object({
  experiment_name: z.string().min(1).max(255),
  description: z.string().optional(),
  control_protocol_id: z.string().uuid().optional(),
  test_protocol_id: z.string().uuid().optional(),
  experiment_type: ExperimentTypeSchema.default('ab_test'),
  target_sample_size: z.number().int().min(1).default(100),
  statistical_power: z.number().min(0).max(1).default(0.8),
  significance_level: z.number().min(0).max(1).default(0.05),
  primary_metric: z.string().max(100).optional(),
  secondary_metrics: z.array(z.string()).default([]),
});

export const UpdateProtocolExperimentRequestSchema = z.object({
  experiment_name: z.string().min(1).max(255).optional(),
  description: z.string().optional(),
  status: ExperimentStatusSchema.optional(),
  start_date: z.string().datetime().optional(),
  end_date: z.string().datetime().optional(),
  target_sample_size: z.number().int().min(1).optional(),
  current_sample_size: z.number().int().min(0).optional(),
  results_data: z.record(z.any()).optional(),
  conclusion: z.string().optional(),
});

export const CreateProtocolEvidenceRequestSchema = z.object({
  protocol_id: z.string().uuid(),
  evidence_type: EvidenceTypeSchema,
  source_reference: z.string().min(1),
  evidence_level: EvidenceLevelSchema.optional(),
  evidence_data: z.record(z.any()).default({}),
  relevance_score: z.number().min(0).max(100).optional(),
  compliance_status: ComplianceStatusSchema.default('compliant'),
  notes: z.string().optional(),
});

export const CreateProtocolImplementationRequestSchema = z.object({
  protocol_version_id: z.string().uuid(),
  implementation_scope: ImplementationScopeSchema,
  target_providers: z.array(z.string().uuid()).default([]),
  implementation_date: z.string().datetime().optional(),
  rollout_strategy: RolloutStrategySchema.default('immediate'),
  training_required: z.boolean().default(true),
  implementation_notes: z.string().optional(),
});

export const UpdateProtocolImplementationRequestSchema = z.object({
  implementation_scope: ImplementationScopeSchema.optional(),
  target_providers: z.array(z.string().uuid()).optional(),
  implementation_date: z.string().datetime().optional(),
  rollout_strategy: RolloutStrategySchema.optional(),
  training_completion_rate: z.number().min(0).max(100).optional(),
  adherence_rate: z.number().min(0).max(100).optional(),
  implementation_notes: z.string().optional(),
  status: ImplementationStatusSchema.optional(),
  success_metrics: z.record(z.any()).optional(),
  rollback_reason: z.string().optional(),
});

// Analytics and reporting validation schemas
export const ProtocolAnalyticsRequestSchema = z.object({
  protocol_version_id: z.string().uuid().optional(),
  analytics_period: AnalyticsPeriodSchema.optional(),
  period_start: z.string().datetime().optional(),
  period_end: z.string().datetime().optional(),
});

export const GenerateOptimizationAnalysisRequestSchema = z.object({
  protocol_id: z.string().uuid(),
  analysis_type: z
    .enum(['performance', 'outcomes', 'cost_effectiveness', 'comprehensive'])
    .default('comprehensive'),
  include_comparisons: z.boolean().default(true),
  date_range: z.object({
    start: z.string().datetime(),
    end: z.string().datetime(),
  }),
});

// API response validation schemas
export const ProtocolApiResponseSchema = <T extends z.ZodTypeAny>(
  dataSchema: T
) =>
  z.object({
    data: dataSchema,
    success: z.boolean(),
    message: z.string().optional(),
    pagination: z
      .object({
        page: z.number().int().min(1),
        per_page: z.number().int().min(1),
        total: z.number().int().min(0),
        total_pages: z.number().int().min(0),
      })
      .optional(),
  });

export const ProtocolApiErrorSchema = z.object({
  error: z.string(),
  details: z.record(z.any()).optional(),
  field_errors: z.record(z.array(z.string())).optional(),
});

// Query parameter validation schemas
export const ProtocolVersionQuerySchema = z.object({
  protocol_name: z.string().optional(),
  approval_status: ApprovalStatusSchema.optional(),
  is_active: z.boolean().optional(),
  created_by: z.string().uuid().optional(),
  page: z.number().int().min(1).default(1),
  per_page: z.number().int().min(1).max(100).default(20),
  sort_by: z
    .enum([
      'protocol_name',
      'version_number',
      'created_at',
      'updated_at',
      'success_rate',
    ])
    .default('created_at'),
  sort_order: z.enum(['asc', 'desc']).default('desc'),
});

export const ProtocolOutcomeQuerySchema = z.object({
  protocol_version_id: z.string().uuid().optional(),
  patient_id: z.string().uuid().optional(),
  success_score_min: z.number().min(0).max(100).optional(),
  success_score_max: z.number().min(0).max(100).optional(),
  outcome_date_start: z.string().datetime().optional(),
  outcome_date_end: z.string().datetime().optional(),
  page: z.number().int().min(1).default(1),
  per_page: z.number().int().min(1).max(100).default(20),
});

export const ProtocolFeedbackQuerySchema = z.object({
  protocol_id: z.string().uuid().optional(),
  provider_id: z.string().uuid().optional(),
  feedback_type: FeedbackTypeSchema.optional(),
  status: FeedbackStatusSchema.optional(),
  priority_level: PriorityLevelSchema.optional(),
  page: z.number().int().min(1).default(1),
  per_page: z.number().int().min(1).max(100).default(20),
});

export const ProtocolExperimentQuerySchema = z.object({
  status: ExperimentStatusSchema.optional(),
  experiment_type: ExperimentTypeSchema.optional(),
  created_by: z.string().uuid().optional(),
  page: z.number().int().min(1).default(1),
  per_page: z.number().int().min(1).max(100).default(20),
});

// Validation helper functions
export const validateProtocolVersionData = (data: unknown) => {
  return ProtocolVersionSchema.parse(data);
};

export const validateCreateProtocolVersionRequest = (data: unknown) => {
  return CreateProtocolVersionRequestSchema.parse(data);
};

export const validateUpdateProtocolVersionRequest = (data: unknown) => {
  return UpdateProtocolVersionRequestSchema.parse(data);
};

export const validateProtocolOutcomeData = (data: unknown) => {
  return ProtocolOutcomeSchema.parse(data);
};

export const validateCreateProtocolOutcomeRequest = (data: unknown) => {
  return CreateProtocolOutcomeRequestSchema.parse(data);
};

export const validateProtocolFeedbackData = (data: unknown) => {
  return ProtocolFeedbackSchema.parse(data);
};

export const validateCreateProtocolFeedbackRequest = (data: unknown) => {
  return CreateProtocolFeedbackRequestSchema.parse(data);
};

export const validateUpdateProtocolFeedbackRequest = (data: unknown) => {
  return UpdateProtocolFeedbackRequestSchema.parse(data);
};

export const validateProtocolExperimentData = (data: unknown) => {
  return ProtocolExperimentSchema.parse(data);
};

export const validateCreateProtocolExperimentRequest = (data: unknown) => {
  return CreateProtocolExperimentRequestSchema.parse(data);
};

export const validateUpdateProtocolExperimentRequest = (data: unknown) => {
  return UpdateProtocolExperimentRequestSchema.parse(data);
};

export const validateProtocolEvidenceData = (data: unknown) => {
  return ProtocolEvidenceSchema.parse(data);
};

export const validateCreateProtocolEvidenceRequest = (data: unknown) => {
  return CreateProtocolEvidenceRequestSchema.parse(data);
};

export const validateProtocolImplementationData = (data: unknown) => {
  return ProtocolImplementationSchema.parse(data);
};

export const validateCreateProtocolImplementationRequest = (data: unknown) => {
  return CreateProtocolImplementationRequestSchema.parse(data);
};

export const validateUpdateProtocolImplementationRequest = (data: unknown) => {
  return UpdateProtocolImplementationRequestSchema.parse(data);
};

export const validateProtocolAnalyticsData = (data: unknown) => {
  return ProtocolAnalyticsSchema.parse(data);
};

export const validateProtocolAnalyticsRequest = (data: unknown) => {
  return ProtocolAnalyticsRequestSchema.parse(data);
};

export const validateGenerateOptimizationAnalysisRequest = (data: unknown) => {
  return GenerateOptimizationAnalysisRequestSchema.parse(data);
};

// Export all schemas for external use
export {
  AnalyticsPeriodSchema,
  ApprovalStatusSchema,
  ComplianceStatusSchema,
  EvidenceLevelSchema,
  EvidenceTypeSchema,
  ExperimentStatusSchema,
  ExperimentTypeSchema,
  FeedbackStatusSchema,
  FeedbackTypeSchema,
  ImplementationScopeSchema,
  ImplementationStatusSchema,
  OptimizationStatusSchema,
  PriorityLevelSchema,
  RolloutStrategySchema,
  VerificationStatusSchema,
};
