// API endpoint: GET/PUT/DELETE /api/automated-protocol-optimization/protocol-versions/[id]
// Story 9.3: Automated protocol optimization - Individual protocol version operations
// Generated by: VoidBeast V4.0

import { type NextRequest, NextResponse } from 'next/server';
import { AutomatedProtocolOptimizationService } from '../../../../lib/services/automated-protocol-optimization';
import { updateProtocolVersionSchema } from '../../../../lib/validations/automated-protocol-optimization';

const service = new AutomatedProtocolOptimizationService();

// GET: Fetch single protocol version by ID
export async function GET(
  _request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const { id } = params;

    if (!id) {
      return NextResponse.json(
        { success: false, error: 'Protocol version ID is required' },
        { status: 400 },
      );
    }

    const protocolVersion = await service.getProtocolVersionById(id);

    if (!protocolVersion) {
      return NextResponse.json(
        { success: false, error: 'Protocol version not found' },
        { status: 404 },
      );
    }

    return NextResponse.json({
      success: true,
      data: protocolVersion,
    });
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to fetch protocol version',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 },
    );
  }
}

// PUT: Update protocol version
export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const { id } = params;
    const body = await request.json();

    if (!id) {
      return NextResponse.json(
        { success: false, error: 'Protocol version ID is required' },
        { status: 400 },
      );
    }

    // Validate request data
    const validation = updateProtocolVersionSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        {
          success: false,
          error: 'Validation failed',
          details: validation.error.format(),
        },
        { status: 400 },
      );
    }

    const updatedProtocolVersion = await service.updateProtocolVersion(
      id,
      validation.data,
    );

    return NextResponse.json({
      success: true,
      data: updatedProtocolVersion,
      message: 'Protocol version updated successfully',
    });
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to update protocol version',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 },
    );
  }
}

// DELETE: Delete protocol version
export async function DELETE(
  _request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const { id } = params;

    if (!id) {
      return NextResponse.json(
        { success: false, error: 'Protocol version ID is required' },
        { status: 400 },
      );
    }

    await service.deleteProtocolVersion(id);

    return NextResponse.json({
      success: true,
      message: 'Protocol version deleted successfully',
    });
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to delete protocol version',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 },
    );
  }
}
