# NeonPro Bunfig - Otimizado para desenvolvimento e testes híbridos
# Configuração estratégica: pnpm para deps, bunx para performance

[install]
# Usar pnpm para instalação de dependências
registry = "https://registry.npmjs.org"
production = false
optional = true
dev = true
peer = true
frozenLockfile = false
# Cache local para performance
cache = ".bun/install-cache"

[run]
# Preload modules comuns para startup mais rápido
preload = [
  "./node_modules/@types/node/index.d.ts",
  "./node_modules/@copilotkit/react-core/dist/index.js",
  "./node_modules/@copilotkit/react-ui/dist/index.js"
]
# Hot reload otimizado
hot = true
# Sem logs verbosos em dev
silent = false

[test]
# Testes otimizados com bunx
timeout = 30000
coverage = true
# Preload testing libs
preload = [
  "./node_modules/vitest/dist/index.js",
  "./.config/testing/vitest.setup.ts"
]

[build]
# Otimizações de build
minify = true
sourcemap = true
target = "node20"
# Externos padrão do monorepo
external = ["react", "react-dom"]

[cache]
# Cache inteligente para turborepo
enabled = true
dir = ".bun/cache"
# Invalidação baseada em mudanças
strategy = "content"