# Bun Configuration for NeonPro Healthcare Platform
# Optimized for performance, security, and healthcare compliance

[install]
# Package installation configuration
cache = true
exact = true
frozen = false
dryRun = false
production = false
optional = true
dev = true
peer = true
registry = "https://registry.npmjs.org/"
telemetry = false

# Performance optimizations for monorepo
concurrent = 8
timeout = 120000
parallel = true

# Healthcare platform specific settings
verify = true
audit = true
checkIntegrity = true

# Trust and security settings
trust = true
save-exact = true

[install.scopes]
# Scoped package registries (if needed for private packages)
# "@neonpro" = "https://npm.pkg.github.com"

[run]
# Script execution configuration
shell = "system"
silent = false
bun = true

# Environment variables for healthcare compliance
[run.env]
NODE_ENV = "development"
HEALTHCARE_COMPLIANCE = "true"
LGPD_ENABLED = "true"
ANVISA_VALIDATION = "true"
BUN_ENV = "development"

[test]
# Testing configuration optimized for healthcare platform
coverage = true
timeout = 60000
preload = ["./vitest.setup.simple.ts"]

[lockfile]
# Lockfile configuration for security and reproducibility
save = true
print = "bun"

# Workspace configuration for monorepo
[workspace]
# Enable workspace support for NeonPro monorepo
enabled = true
