# NeonPro Bunfig - Healthcare-Optimized Configuration
# Optimized for maximum performance, compliance, and reliability

[install]
# Native Bun package manager with healthcare compliance
registry = "https://registry.npmjs.org"
production = false
optional = true
dev = true
peer = true
frozenLockfile = true
# Healthcare compliance: exact versions
exact = true
# Aggressive caching for performance
cache = ".bun/install-cache"
# Prefer ES modules for better compatibility
esModule = true
# Dedupe dependencies for efficiency
dedupe = true

[run]
# Preload critical healthcare modules
preload = [
  "./node_modules/@types/node/index.d.ts",
  "./node_modules/@supabase/supabase-js/dist/index.js",
  "./node_modules/zod/lib/index.js",
]
# Hot reload optimized for development
hot = true
# Optimized logging for healthcare debugging
silent = false
# PATH resolution for local binaries
env = { "PATH": "./node_modules/.bin:$PATH" }

[test]
# Healthcare test optimizations
timeout = 60000
coverage = true
# Preload healthcare testing libraries
preload = [
  "./src/test/setup/bun-test-preload.ts"
]
# Healthcare compliance test patterns
testNamePattern = ".*healthcare.*|.*compliance.*|.*lgpd.*"

[build]
# Healthcare-optimized build settings
minify = true
sourcemap = true
target = "node20"
# Healthcare external dependencies
external = ["react", "react-dom", "@supabase/supabase-js"]
# Optimized for healthcare workloads
splitting = true
treeshake = true
# Healthcare compliance metadata
metafile = true

# Cache optimization for healthcare builds
[cache.build]
enabled = true
dir = ".bun/build-cache"
# Content-based invalidation for compliance
strategy = "content"
# Healthcare audit trail
audit = true
# Cache healthcare builds longer
max_age = 86400 # 24 hours

[cache]
# Healthcare-compliant caching strategy
enabled = true
dir = ".bun/cache"
# Content-based invalidation for compliance
strategy = "content"
# Healthcare audit trail
audit = true

# Performance optimizations for healthcare workloads
[optimize]
# Enable Bun's optimizer for healthcare apps
enabled = true
# Dedupe healthcare dependencies
dedupe = true
# ES modules for better performance
esModule = true
# Skip unnecessary transpilation
skipTranspile = ["react", "react-dom"]

# Healthcare-specific settings
[healthcare]
# Enable compliance validation
compliance = true
# Healthcare data residency
dataResidency = "local"
# Audit logging for healthcare
auditLogging = true
# LGPD compliance mode
lgpdMode = true
