// NEONPRO Drizzle Configuration
// Database Migration and Schema Management
// Generated by VIBECODE SYSTEM V4.0 - Architectural Optimization

import { config } from "dotenv";
import { defineConfig } from "drizzle-kit";

// Load environment variables
config({ path: ".env.local" });

export default defineConfig({
  schema: "./src/lib/schema.ts",
  out: "./drizzle",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL || "postgresql://localhost:5432/neonpro",
  },
  verbose: true,
  strict: true,
});
