packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"
  
# Explicit core packages for new 8-package architecture
# - packages/types
# - packages/shared  
# - packages/database
# - packages/ai-services
# - packages/healthcare-core
# - packages/security-compliance
# - packages/api-gateway
# - packages/ui
