# NEONPRO Healthcare Artillery Load Testing Configuration
# Based on Medplum healthcare load testing patterns
# Healthcare-grade performance validation with LGPD compliance

config:
  target: "http://localhost:3000"
  phases:
    # Warm-up phase for healthcare systems
    - duration: 30
      arrivalRate: 5
      name: "Healthcare System Warmup"

    # Light load for normal clinic operations
    - duration: 120
      arrivalRate: 10
      rampTo: 25
      name: "Normal Clinic Load"

    # Peak load for busy clinic hours
    - duration: 180
      arrivalRate: 25
      rampTo: 50
      name: "Peak Clinic Hours"

    # Stress test for system limits
    - duration: 60
      arrivalRate: 50
      rampTo: 100
      name: "Healthcare System Stress Test"

  # Healthcare API Authentication
  variables:
    auth: "Bearer {{ $env.TEST_AUTH_TOKEN }}"
    tenantId: '{{ $env.TEST_TENANT_ID || "test-tenant-healthcare" }}'

  # Healthcare Performance Requirements
  ensure:
    # Critical healthcare response times
    - expression: "p(95) < 500" # 95% under 500ms
      title: "Healthcare API p95 < 500ms"

    - expression: "p(99) < 1000" # 99% under 1s
      title: "Healthcare API p99 < 1s"

    # Healthcare availability requirement
    - expression: "rate(200) > 0.99"
      title: "Healthcare API availability > 99%"

    # Error rate limits for healthcare
    - expression: "rate(500) < 0.01"
      title: "Healthcare API error rate < 1%"

scenarios:
  # Healthcare System Health Check
  - name: "Healthcare API Health Check"
    weight: 10
    flow:
      - loop:
          - get:
              url: "/api/health"
              headers:
                X-Tenant-ID: "{{ tenantId }}"
              expect:
                - statusCode: 200
                - hasProperty: "status"
        count: 5

  # Patient Management Workflow
  - name: "Patient Management Load Test"
    weight: 40
    flow:
      - loop:
          # Create patient with LGPD compliance
          - post:
              url: "/api/patients"
              headers:
                Authorization: "{{ auth }}"
                X-Tenant-ID: "{{ tenantId }}"
                Content-Type: "application/json"
              json:
                name: "{{ $randomString() }} {{ $randomString() }}"
                email: "{{ $randomString() }}@test-clinic.com"
                phone: "+5511{{ $randomInt(100000000, 999999999) }}"
                dateOfBirth: "1990-01-01"
                lgpdConsent: true
              capture:
                - json: "$.data.id"
                  as: "patientId"
              expect:
                - statusCode: [200, 201]
                - hasProperty: "data.id"
          # Read patient data
          - get:
              url: "/api/patients/{{ patientId }}"
              headers:
                Authorization: "{{ auth }}"
                X-Tenant-ID: "{{ tenantId }}"
              expect:
                - statusCode: 200
                - hasProperty: "data.name"

          # Search patients (LGPD compliant)
          - get:
              url: "/api/patients?limit=10&page=1"
              headers:
                Authorization: "{{ auth }}"
                X-Tenant-ID: "{{ tenantId }}"
              expect:
                - statusCode: 200
                - hasProperty: "data"
        count: 3

  # Appointment Scheduling Load Test
  - name: "Appointment Scheduling Load Test"
    weight: 30
    flow:
      - loop:
          # Create appointment
          - post:
              url: "/api/appointments"
              headers:
                Authorization: "{{ auth }}"
                X-Tenant-ID: "{{ tenantId }}"
                Content-Type: "application/json"
              json:
                patientId: "test-patient-{{ $randomString() }}"
                providerId: "test-provider-{{ $randomString() }}"
                scheduledAt: "{{ $randomISO() }}"
                procedure: "Consultation"
                status: "scheduled"
              capture:
                - json: "$.data.id"
                  as: "appointmentId"
              expect:
                - statusCode: [200, 201]

          # Get appointment details
          - get:
              url: "/api/appointments/{{ appointmentId }}"
              headers:
                Authorization: "{{ auth }}"
                X-Tenant-ID: "{{ tenantId }}"
              expect:
                - statusCode: 200
        count: 2

  # Healthcare Analytics Load Test
  - name: "Healthcare Analytics Load Test"
    weight: 15
    flow:
      - loop:
          # Get analytics dashboard
          - get:
              url: "/api/analytics"
              headers:
                Authorization: "{{ auth }}"
                X-Tenant-ID: "{{ tenantId }}"
              expect:
                - statusCode: 200
                - hasProperty: "data"

          # Performance metrics
          - get:
              url: "/api/analytics/performance"
              headers:
                Authorization: "{{ auth }}"
                X-Tenant-ID: "{{ tenantId }}"
              expect:
                - statusCode: 200
        count: 1

  # LGPD Compliance Load Test
  - name: "LGPD Compliance Validation"
    weight: 5
    flow:
      - loop:
          # Validate LGPD compliance
          - get:
              url: "/api/compliance/lgpd/status"
              headers:
                Authorization: "{{ auth }}"
                X-Tenant-ID: "{{ tenantId }}"
              expect:
                - statusCode: 200
                - hasProperty: "compliance"
        count: 1
