# NeonPro AI Services - Alerting Rules
# Comprehensive alerting for AI healthcare platform
# Includes performance, availability, compliance, and business metrics

groups:
  # =============================================================================
  # AI SERVICE PERFORMANCE ALERTS
  # =============================================================================
  - name: ai_service_performance
    interval: 30s
    rules:
      - alert: AIServiceHighResponseTime
        expr: ai_service_response_time_milliseconds{quantile="0.95"} > 3000
        for: 2m
        labels:
          severity: warning
          component: ai-service
          category: performance
        annotations:
          summary: "AI service {{ $labels.service_name }} has high response time"
          description: "95th percentile response time for {{ $labels.service_name }} is {{ $value }}ms, exceeding 3 second threshold"
          runbook_url: "https://docs.neonpro.com.br/runbooks/ai-service-performance"
          dashboard_url: "https://grafana.neonpro.com.br/d/ai-services/ai-services-overview"

      - alert: AIServiceHighErrorRate
        expr: rate(ai_service_errors_total[5m]) / rate(ai_service_requests_total[5m]) > 0.05
        for: 1m
        labels:
          severity: critical
          component: ai-service
          category: reliability
        annotations:
          summary: "AI service {{ $labels.service_name }} has high error rate"
          description: "Error rate for {{ $labels.service_name }} is {{ $value | humanizePercentage }}, exceeding 5% threshold"
          impact: "Users may experience failures when using AI features"
          action: "Check service logs and recent deployments"

      - alert: AIServiceLowConfidence
        expr: ai_service_confidence_score < 0.7
        for: 5m
        labels:
          severity: warning
          component: ai-service
          category: quality
        annotations:
          summary: "AI service {{ $labels.service_name }} confidence score is low"
          description: "Average confidence score is {{ $value }}, below 70% threshold"
          impact: "AI responses may be less reliable"
          action: "Review model performance and consider retraining"

      - alert: AIServiceHighTokenConsumption
        expr: rate(ai_service_tokens_consumed_total[1h]) > 100000
        for: 10m
        labels:
          severity: warning
          component: ai-service
          category: cost
        annotations:
          summary: "High token consumption detected"
          description: "Token consumption rate is {{ $value }} tokens/hour for {{ $labels.service_name }}"
          impact: "Increased AI service costs"
          action: "Review usage patterns and implement optimization"

  # =============================================================================
  # UNIVERSAL CHAT SPECIFIC ALERTS
  # =============================================================================
  - name: universal_chat_alerts
    interval: 30s
    rules:
      - alert: UniversalChatHighLatency
        expr: histogram_quantile(0.95, rate(ai_chat_message_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
          component: universal-chat
          category: performance
        annotations:
          summary: "Universal Chat service has high latency"
          description: "95th percentile chat response time is {{ $value }}s"
          impact: "Poor user experience in chat interactions"

      - alert: UniversalChatSessionCreationFailure
        expr: rate(ai_chat_session_creation_failures_total[5m]) > 0.1
        for: 1m
        labels:
          severity: critical
          component: universal-chat
          category: reliability
        annotations:
          summary: "High rate of chat session creation failures"
          description: "Session creation failure rate: {{ $value }}/min"
          impact: "Users cannot start new chat conversations"

      - alert: UniversalChatEmergencyDetection
        expr: increase(ai_chat_emergency_detections_total[1m]) > 0
        for: 0s
        labels:
          severity: critical
          component: universal-chat
          category: safety
          priority: immediate
        annotations:
          summary: "Emergency situation detected in chat"
          description: "{{ $value }} emergency situations detected in chat sessions"
          impact: "Patient safety concern - immediate attention required"
          action: "Notify on-call medical staff immediately"

      - alert: UniversalChatComplianceViolation
        expr: increase(ai_chat_compliance_violations_total[5m]) > 0
        for: 0s
        labels:
          severity: high
          component: universal-chat
          category: compliance
        annotations:
          summary: "Compliance violation detected in chat"
          description: "{{ $value }} compliance violations ({{ $labels.violation_type }})"
          impact: "Potential regulatory compliance issues"
          action: "Review conversation logs and implement corrective measures"

  # =============================================================================
  # COMPLIANCE AUTOMATION ALERTS
  # =============================================================================
  - name: compliance_automation_alerts
    interval: 60s
    rules:
      - alert: LGPDComplianceFailure
        expr: increase(ai_compliance_lgpd_violations_total[10m]) > 0
        for: 0s
        labels:
          severity: critical
          component: compliance-automation
          category: lgpd
          regulation: "LGPD"
        annotations:
          summary: "LGPD compliance violation detected"
          description: "{{ $value }} LGPD violations detected: {{ $labels.violation_code }}"
          impact: "Risk of regulatory penalties and data protection violations"
          action: "Immediately review data processing activities and implement fixes"

      - alert: ANVISAComplianceFailure
        expr: increase(ai_compliance_anvisa_violations_total[10m]) > 0
        for: 0s
        labels:
          severity: critical
          component: compliance-automation
          category: anvisa
          regulation: "ANVISA"
        annotations:
          summary: "ANVISA compliance violation detected"
          description: "{{ $value }} ANVISA violations detected: {{ $labels.violation_code }}"
          impact: "Risk of health regulatory penalties"
          action: "Review medical data handling and ensure ANVISA compliance"

      - alert: CFMComplianceFailure
        expr: increase(ai_compliance_cfm_violations_total[10m]) > 0
        for: 0s
        labels:
          severity: critical
          component: compliance-automation
          category: cfm
          regulation: "CFM"
        annotations:
          summary: "CFM compliance violation detected"
          description: "{{ $value }} CFM violations detected: {{ $labels.violation_code }}"
          impact: "Risk of medical council penalties"
          action: "Review medical practice compliance with CFM regulations"

      - alert: ComplianceAuditTrailGaps
        expr: increase(ai_compliance_audit_gaps_total[1h]) > 5
        for: 5m
        labels:
          severity: warning
          component: compliance-automation
          category: audit
        annotations:
          summary: "Gaps detected in compliance audit trail"
          description: "{{ $value }} audit trail gaps detected in the last hour"
          impact: "Potential compliance audit failures"
          action: "Review audit logging configuration and data integrity"

  # =============================================================================
  # INFRASTRUCTURE ALERTS
  # =============================================================================
  - name: ai_infrastructure_alerts
    interval: 30s
    rules:
      - alert: RedisConnectionFailure
        expr: redis_connected_clients == 0
        for: 1m
        labels:
          severity: critical
          component: redis
          category: infrastructure
        annotations:
          summary: "Redis has no connected clients"
          description: "Redis cache service appears to be disconnected"
          impact: "AI services may experience degraded performance without caching"

      - alert: RedisCacheHitRateLow
        expr: redis_cache_hit_rate < 0.8
        for: 10m
        labels:
          severity: warning
          component: redis
          category: performance
        annotations:
          summary: "Redis cache hit rate is low"
          description: "Cache hit rate is {{ $value | humanizePercentage }}, below 80% target"
          impact: "Increased latency and database load"
          action: "Review caching strategy and TTL settings"

      - alert: DatabaseConnectionPoolExhausted
        expr: database_connection_pool_active >= database_connection_pool_max * 0.9
        for: 2m
        labels:
          severity: critical
          component: database
          category: infrastructure
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "{{ $value }} active connections out of {{ $labels.max_connections }} maximum"
          impact: "New database operations may be blocked"
          action: "Investigate connection leaks and consider scaling"

  # =============================================================================
  # BUSINESS METRICS ALERTS
  # =============================================================================
  - name: ai_business_metrics
    interval: 60s
    rules:
      - alert: AIServiceUsageSpike
        expr: rate(ai_service_requests_total[10m]) > 1000
        for: 5m
        labels:
          severity: info
          component: ai-service
          category: business
        annotations:
          summary: "Unusual spike in AI service usage"
          description: "Request rate: {{ $value }}/min for {{ $labels.service_name }}"
          impact: "Potential increased costs and resource usage"
          action: "Monitor for capacity constraints and cost implications"

      - alert: PatientSafetyAlert
        expr: increase(ai_patient_safety_concerns_total[5m]) > 0
        for: 0s
        labels:
          severity: critical
          component: ai-service
          category: safety
          priority: immediate
        annotations:
          summary: "Patient safety concern detected"
          description: "{{ $value }} safety concerns flagged by AI system"
          impact: "Immediate patient safety risk"
          action: "Notify medical staff and initiate safety protocols"

      - alert: AIServiceCostThresholdExceeded
        expr: ai_service_cost_hourly > 100
        for: 30m
        labels:
          severity: warning
          component: ai-service
          category: cost
        annotations:
          summary: "AI service costs exceeding budget threshold"
          description: "Hourly cost: ${{ $value }} for {{ $labels.service_name }}"
          impact: "Budget overrun risk"
          action: "Review usage patterns and implement cost controls"

  # =============================================================================
  # AVAILABILITY AND UPTIME ALERTS
  # =============================================================================
  - name: ai_availability_alerts
    interval: 30s
    rules:
      - alert: AIServiceDown
        expr: up{job=~"ai-.*"} == 0
        for: 1m
        labels:
          severity: critical
          component: ai-service
          category: availability
        annotations:
          summary: "AI service {{ $labels.job }} is down"
          description: "Service has been down for more than 1 minute"
          impact: "Complete service unavailability"
          action: "Check service health and restart if necessary"

      - alert: AIServiceDegradedPerformance
        expr: (rate(ai_service_requests_total[5m]) > 0) and (rate(ai_service_errors_total[5m]) / rate(ai_service_requests_total[5m]) > 0.1)
        for: 3m
        labels:
          severity: warning
          component: ai-service
          category: availability
        annotations:
          summary: "AI service {{ $labels.service_name }} performance degraded"
          description: "Error rate: {{ $value | humanizePercentage }}"
          impact: "Users experiencing service issues"
          action: "Investigate service health and recent changes"

      - alert: HealthCheckFailure
        expr: probe_success{job="blackbox-http"} == 0
        for: 2m
        labels:
          severity: critical
          component: health-check
          category: availability
        annotations:
          summary: "Health check failure for {{ $labels.instance }}"
          description: "Endpoint {{ $labels.instance }} failing health checks"
          impact: "Service may be unavailable to users"

  # =============================================================================
  # SECURITY ALERTS
  # =============================================================================
  - name: ai_security_alerts
    interval: 30s
    rules:
      - alert: SuspiciousAIServiceAccess
        expr: rate(ai_service_requests_total{status_code=~"4[0-9][0-9]"}[5m]) > 10
        for: 2m
        labels:
          severity: warning
          component: ai-service
          category: security
        annotations:
          summary: "High rate of 4xx errors in AI service"
          description: "{{ $value }} 4xx errors/min - possible attack or misconfiguration"
          impact: "Potential security threat or service issues"
          action: "Review access logs and implement security measures if needed"

      - alert: UnauthorizedComplianceAccess
        expr: increase(ai_compliance_unauthorized_access_total[5m]) > 0
        for: 0s
        labels:
          severity: high
          component: compliance-automation
          category: security
        annotations:
          summary: "Unauthorized access to compliance data detected"
          description: "{{ $value }} unauthorized access attempts"
          impact: "Potential data breach of sensitive compliance information"
          action: "Investigate access logs and strengthen access controls"

  # =============================================================================
  # MODEL PERFORMANCE ALERTS
  # =============================================================================
  - name: ai_model_performance
    interval: 300s
    rules:
      - alert: AIModelDrift
        expr: ai_model_accuracy < 0.85
        for: 15m
        labels:
          severity: warning
          component: ai-model
          category: quality
        annotations:
          summary: "AI model accuracy degradation detected"
          description: "Model accuracy: {{ $value | humanizePercentage }} for {{ $labels.model_name }}"
          impact: "Reduced quality of AI predictions and recommendations"
          action: "Consider model retraining or updating training data"

      - alert: AIModelTrainingRequired
        expr: time() - ai_model_last_training_timestamp > 2592000  # 30 days
        for: 1h
        labels:
          severity: info
          component: ai-model
          category: maintenance
        annotations:
          summary: "AI model {{ $labels.model_name }} requires retraining"
          description: "Model has not been retrained for {{ $value | humanizeDuration }}"
          impact: "Model performance may degrade over time"
          action: "Schedule model retraining with updated data"