// Backend service for Automated Protocol Optimization System
// Story 9.3: Automated protocol optimization with continuous improvement
// Generated by: VoidBeast V4.0

import type {
    CreateProtocolEvidenceRequest,
    CreateProtocolExperimentRequest,
    CreateProtocolFeedbackRequest,
    CreateProtocolImplementationRequest,
    CreateProtocolOutcomeRequest,
    CreateProtocolVersionRequest,
    OptimizationResult,
    ProtocolAnalytics,
    ProtocolAnalyticsRequest,
    ProtocolEvidence,
    ProtocolExperiment,
    ProtocolExperimentResults,
    ProtocolFeedback,
    ProtocolImplementation,
    ProtocolOptimizationAnalysis,
    ProtocolOptimizationQueue,
    ProtocolOutcome,
    ProtocolPerformanceReport,
    ProtocolVersion,
    ProtocolVersionWithAnalytics,
    UpdateProtocolExperimentRequest,
    UpdateProtocolFeedbackRequest,
    UpdateProtocolImplementationRequest,
    UpdateProtocolVersionRequest,
} from '../../types/automated-protocol-optimization';
import { createClient } from '../../utils/supabase/client';

export class AutomatedProtocolOptimizationService {
  // Supabase client created per method for proper request context

  // Protocol Version Management
  async createProtocolVersion(data: CreateProtocolVersionRequest): Promise<ProtocolVersion> {
    const supabase = await createClient();
    const { data: result, error } = await supabase
      .from('protocol_versions')
      .insert({
        ...data,
        created_by: (await supabase.auth.getUser()).data.user?.id,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) throw new Error(`Failed to create protocol version: ${error.message}`);
    return result;
  }

  async getProtocolVersions(filters?: {
    protocol_name?: string;
    approval_status?: string;
    is_active?: boolean;
    page?: number;
    per_page?: number;
  }): Promise<{ data: ProtocolVersionWithAnalytics[]; total: number }> {
    let query = supabase
      .from('protocol_versions')
      .select(`
        *,
        latest_analytics:protocol_analytics(*)
      `);

    if (filters?.protocol_name) {
      query = query.ilike('protocol_name', `%${filters.protocol_name}%`);
    }
    if (filters?.approval_status) {
      query = query.eq('approval_status', filters.approval_status);
    }
    if (filters?.is_active !== undefined) {
      query = query.eq('is_active', filters.is_active);
    }

    const page = filters?.page || 1;
    const per_page = filters?.per_page || 20;
    const from = (page - 1) * per_page;
    const to = from + per_page - 1;

    const { data, error, count } = await query
      .range(from, to)
      .order('created_at', { ascending: false });

    if (error) throw new Error(`Failed to fetch protocol versions: ${error.message}`);

    // Add outcome and feedback counts for each protocol
    const protocolsWithCounts = await Promise.all(
      (data || []).map(async (protocol) => {
        const [outcomeCount, feedbackCount] = await Promise.all([
          this.getProtocolOutcomeCount(protocol.id),
          this.getProtocolFeedbackCount(protocol.id),
        ]);

        return {
          ...protocol,
          outcome_count: outcomeCount,
          feedback_count: feedbackCount,
        };
      })
    );

    return { data: protocolsWithCounts, total: count || 0 };
  }

  async getProtocolVersionById(id: string): Promise<ProtocolVersion | null> {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from('protocol_versions')
      .select('*')
      .eq('id', id)
      .single();

    if (error) throw new Error(`Failed to fetch protocol version: ${error.message}`);
    return data;
  }

  async updateProtocolVersion(id: string, data: UpdateProtocolVersionRequest): Promise<ProtocolVersion> {
    const supabase = await createClient();
    const { data: result, error } = await supabase
      .from('protocol_versions')
      .update({
        ...data,
        updated_at: new Date().toISOString(),
      })
      .eq('id', id)
      .select()
      .single();

    if (error) throw new Error(`Failed to update protocol version: ${error.message}`);
    return result;
  }

  async deleteProtocolVersion(id: string): Promise<void> {
    const { error } = await supabase
      .from('protocol_versions')
      .delete()
      .eq('id', id);

    if (error) throw new Error(`Failed to delete protocol version: ${error.message}`);
  }

  // Protocol Outcome Tracking
  async createProtocolOutcome(data: CreateProtocolOutcomeRequest): Promise<ProtocolOutcome> {
    const supabase = await createClient();
    const { data: result, error } = await supabase
      .from('protocol_outcomes')
      .insert({
        ...data,
        recorded_by: (await supabase.auth.getUser()).data.user?.id,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) throw new Error(`Failed to create protocol outcome: ${error.message}`);

    // Trigger optimization analysis after recording outcome
    await this.triggerOptimizationAnalysis(data.protocol_version_id);

    return result;
  }

  async getProtocolOutcomes(filters?: {
    protocol_version_id?: string;
    patient_id?: string;
    success_score_min?: number;
    success_score_max?: number;
    page?: number;
    per_page?: number;
  }): Promise<{ data: ProtocolOutcome[]; total: number }> {
    let query = supabase.from('protocol_outcomes').select('*');

    if (filters?.protocol_version_id) {
      query = query.eq('protocol_version_id', filters.protocol_version_id);
    }
    if (filters?.patient_id) {
      query = query.eq('patient_id', filters.patient_id);
    }
    if (filters?.success_score_min !== undefined) {
      query = query.gte('success_score', filters.success_score_min);
    }
    if (filters?.success_score_max !== undefined) {
      query = query.lte('success_score', filters.success_score_max);
    }

    const page = filters?.page || 1;
    const per_page = filters?.per_page || 20;
    const from = (page - 1) * per_page;
    const to = from + per_page - 1;

    const { data, error, count } = await query
      .range(from, to)
      .order('outcome_date', { ascending: false });

    if (error) throw new Error(`Failed to fetch protocol outcomes: ${error.message}`);
    return { data: data || [], total: count || 0 };
  }

  private async getProtocolOutcomeCount(protocol_version_id: string): Promise<number> {
    const { count, error } = await supabase
      .from('protocol_outcomes')
      .select('*', { count: 'exact', head: true })
      .eq('protocol_version_id', protocol_version_id);

    if (error) throw new Error(`Failed to get outcome count: ${error.message}`);
    return count || 0;
  }

  // Protocol Feedback Management
  async createProtocolFeedback(data: CreateProtocolFeedbackRequest): Promise<ProtocolFeedback> {
    const supabase = await createClient();
    const { data: result, error } = await supabase
      .from('protocol_feedback')
      .insert({
        ...data,
        provider_id: (await supabase.auth.getUser()).data.user?.id,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) throw new Error(`Failed to create protocol feedback: ${error.message}`);

    // Process high-priority feedback immediately
    if (data.priority_level === 'high' || data.priority_level === 'critical') {
      await this.processPriorityFeedback(result.id);
    }

    return result;
  }

  async getProtocolFeedback(filters?: {
    protocol_id?: string;
    provider_id?: string;
    feedback_type?: string;
    status?: string;
    priority_level?: string;
    page?: number;
    per_page?: number;
  }): Promise<{ data: ProtocolFeedback[]; total: number }> {
    let query = supabase.from('protocol_feedback').select('*');

    if (filters?.protocol_id) {
      query = query.eq('protocol_id', filters.protocol_id);
    }
    if (filters?.provider_id) {
      query = query.eq('provider_id', filters.provider_id);
    }
    if (filters?.feedback_type) {
      query = query.eq('feedback_type', filters.feedback_type);
    }
    if (filters?.status) {
      query = query.eq('status', filters.status);
    }
    if (filters?.priority_level) {
      query = query.eq('priority_level', filters.priority_level);
    }

    const page = filters?.page || 1;
    const per_page = filters?.per_page || 20;
    const from = (page - 1) * per_page;
    const to = from + per_page - 1;

    const { data, error, count } = await query
      .range(from, to)
      .order('created_at', { ascending: false });

    if (error) throw new Error(`Failed to fetch protocol feedback: ${error.message}`);
    return { data: data || [], total: count || 0 };
  }

  async updateProtocolFeedback(id: string, data: UpdateProtocolFeedbackRequest): Promise<ProtocolFeedback> {
    const supabase = await createClient();
    const { data: result, error } = await supabase
      .from('protocol_feedback')
      .update({
        ...data,
        reviewed_by: (await supabase.auth.getUser()).data.user?.id,
        reviewed_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .eq('id', id)
      .select()
      .single();

    if (error) throw new Error(`Failed to update protocol feedback: ${error.message}`);
    return result;
  }

  private async getProtocolFeedbackCount(protocol_id: string): Promise<number> {
    const { count, error } = await supabase
      .from('protocol_feedback')
      .select('*', { count: 'exact', head: true })
      .eq('protocol_id', protocol_id);

    if (error) throw new Error(`Failed to get feedback count: ${error.message}`);
    return count || 0;
  }

  // Optimization Analysis Engine
  async triggerOptimizationAnalysis(protocol_id: string): Promise<OptimizationResult> {
    // Get protocol data and recent outcomes
    const [protocol, outcomes, feedback] = await Promise.all([
      this.getProtocolVersionById(protocol_id),
      this.getProtocolOutcomes({ protocol_version_id: protocol_id }),
      this.getProtocolFeedback({ protocol_id }),
    ]);

    if (!protocol) {
      throw new Error('Protocol not found for optimization analysis');
    }

    // Perform automated analysis
    const analysis = await this.performOptimizationAnalysis(protocol, outcomes.data, feedback.data);

    // Store optimization results
    const { data: result, error } = await supabase
      .from('optimization_results')
      .insert({
        protocol_id,
        optimization_type: 'automated_analysis',
        improvement_metrics: analysis.metrics,
        validation_data: analysis.validation,
        confidence_score: analysis.confidence,
        statistical_significance: analysis.significance,
        recommendation_data: analysis.recommendations,
        automated_analysis: analysis.full_analysis,
        human_review_required: analysis.confidence < 80,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) throw new Error(`Failed to store optimization results: ${error.message}`);
    return result;
  }

  private async performOptimizationAnalysis(
    protocol: ProtocolVersion,
    outcomes: ProtocolOutcome[],
    feedback: ProtocolFeedback[]
  ): Promise<{
    metrics: Record<string, any>;
    validation: Record<string, any>;
    confidence: number;
    significance: number;
    recommendations: Record<string, any>;
    full_analysis: Record<string, any>;
  }> {
    // Calculate performance metrics
    const successRate = outcomes.length > 0 
      ? outcomes.reduce((sum, o) => sum + o.success_score, 0) / outcomes.length
      : 0;

    const averageSatisfaction = outcomes
      .filter(o => o.patient_satisfaction !== null)
      .reduce((sum, o) => sum + (o.patient_satisfaction || 0), 0) / 
      outcomes.filter(o => o.patient_satisfaction !== null).length || 0;

    const complicationRate = outcomes.filter(o => 
      Array.isArray(o.complications) && o.complications.length > 0
    ).length / outcomes.length * 100;

    // Analyze feedback patterns
    const criticalFeedback = feedback.filter(f => f.priority_level === 'critical').length;
    const improvementSuggestions = feedback.filter(f => 
      f.feedback_type === 'improvement' || f.feedback_type === 'suggestion'
    ).length;

    // Generate recommendations based on analysis
    const recommendations = [];
    
    if (successRate < 75) {
      recommendations.push({
        type: 'success_rate_improvement',
        priority: 'high',
        suggestion: 'Consider reviewing protocol steps with low success rates',
        potential_improvement: 15,
      });
    }

    if (complicationRate > 10) {
      recommendations.push({
        type: 'complication_reduction',
        priority: 'critical',
        suggestion: 'Implement additional safety measures to reduce complications',
        potential_improvement: 20,
      });
    }

    if (averageSatisfaction < 7) {
      recommendations.push({
        type: 'satisfaction_improvement',
        priority: 'medium',
        suggestion: 'Review patient communication and expectations management',
        potential_improvement: 10,
      });
    }

    // Calculate confidence score based on data quality and quantity
    const confidence = Math.min(100, 
      (outcomes.length * 2) + 
      (feedback.length * 1.5) + 
      (protocol.optimization_data ? 10 : 0)
    );

    // Calculate statistical significance (simplified)
    const significance = outcomes.length >= 30 ? 0.05 : 0.1;

    return {
      metrics: {
        success_rate: successRate,
        average_satisfaction: averageSatisfaction,
        complication_rate: complicationRate,
        total_outcomes: outcomes.length,
        total_feedback: feedback.length,
        critical_feedback_count: criticalFeedback,
      },
      validation: {
        sample_size: outcomes.length,
        feedback_quality: feedback.length > 0 ? 'adequate' : 'limited',
        data_completeness: outcomes.length > 10 ? 'good' : 'limited',
      },
      confidence,
      significance,
      recommendations: {
        high_priority: recommendations.filter(r => r.priority === 'critical' || r.priority === 'high'),
        medium_priority: recommendations.filter(r => r.priority === 'medium'),
        all_recommendations: recommendations,
      },
      full_analysis: {
        analyzed_at: new Date().toISOString(),
        protocol_version: protocol.version_number,
        analysis_scope: {
          outcomes_period: outcomes.length > 0 ? {
            start: Math.min(...outcomes.map(o => new Date(o.outcome_date).getTime())),
            end: Math.max(...outcomes.map(o => new Date(o.outcome_date).getTime())),
          } : null,
          feedback_summary: {
            total: feedback.length,
            by_type: feedback.reduce((acc, f) => {
              acc[f.feedback_type] = (acc[f.feedback_type] || 0) + 1;
              return acc;
            }, {} as Record<string, number>),
          },
        },
      },
    };
  }

  async getOptimizationResults(protocol_id?: string): Promise<ProtocolOptimizationQueue> {
    let query = supabase.from('optimization_results').select('*');

    if (protocol_id) {
      query = query.eq('protocol_id', protocol_id);
    }

    const { data, error } = await query.order('created_at', { ascending: false });

    if (error) throw new Error(`Failed to fetch optimization results: ${error.message}`);

    const results = data || [];

    return {
      high_priority: results.filter(r => 
        r.confidence_score && r.confidence_score >= 80 && 
        r.improvement_metrics?.recommendations?.high_priority?.length > 0
      ),
      medium_priority: results.filter(r => 
        r.confidence_score && r.confidence_score >= 60 && r.confidence_score < 80
      ),
      low_priority: results.filter(r => 
        r.confidence_score && r.confidence_score < 60
      ),
      review_required: results.filter(r => r.human_review_required),
    };
  }

  // A/B Testing and Experiments
  async createProtocolExperiment(data: CreateProtocolExperimentRequest): Promise<ProtocolExperiment> {
    const supabase = await createClient();
    const { data: result, error } = await supabase
      .from('protocol_experiments')
      .insert({
        ...data,
        created_by: (await supabase.auth.getUser()).data.user?.id,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) throw new Error(`Failed to create protocol experiment: ${error.message}`);
    return result;
  }

  async updateProtocolExperiment(id: string, data: UpdateProtocolExperimentRequest): Promise<ProtocolExperiment> {
    const supabase = await createClient();
    const { data: result, error } = await supabase
      .from('protocol_experiments')
      .update({
        ...data,
        updated_at: new Date().toISOString(),
      })
      .eq('id', id)
      .select()
      .single();

    if (error) throw new Error(`Failed to update protocol experiment: ${error.message}`);
    return result;
  }

  async getProtocolExperiments(filters?: {
    status?: string;
    experiment_type?: string;
    page?: number;
    per_page?: number;
  }): Promise<{ data: ProtocolExperiment[]; total: number }> {
    let query = supabase.from('protocol_experiments').select('*');

    if (filters?.status) {
      query = query.eq('status', filters.status);
    }
    if (filters?.experiment_type) {
      query = query.eq('experiment_type', filters.experiment_type);
    }

    const page = filters?.page || 1;
    const per_page = filters?.per_page || 20;
    const from = (page - 1) * per_page;
    const to = from + per_page - 1;

    const { data, error, count } = await query
      .range(from, to)
      .order('created_at', { ascending: false });

    if (error) throw new Error(`Failed to fetch protocol experiments: ${error.message}`);
    return { data: data || [], total: count || 0 };
  }

  async analyzeExperimentResults(experiment_id: string): Promise<ProtocolExperimentResults> {
    const supabase = await createClient();
    const { data: experiment, error } = await supabase
      .from('protocol_experiments')
      .select('*')
      .eq('id', experiment_id)
      .single();

    if (error) throw new Error(`Failed to fetch experiment: ${error.message}`);

    // Get outcomes for both control and test protocols
    const [controlOutcomes, testOutcomes] = await Promise.all([
      experiment.control_protocol_id 
        ? this.getProtocolOutcomes({ protocol_version_id: experiment.control_protocol_id })
        : { data: [], total: 0 },
      experiment.test_protocol_id 
        ? this.getProtocolOutcomes({ protocol_version_id: experiment.test_protocol_id })
        : { data: [], total: 0 },
    ]);

    // Perform statistical analysis
    const controlMean = controlOutcomes.data.length > 0 
      ? (controlOutcomes.data as any[]).reduce((sum, o) => sum + o.success_score, 0) / controlOutcomes.data.length
      : 0;

    const testMean = testOutcomes.data.length > 0 
      ? (testOutcomes.data as any[]).reduce((sum, o) => sum + o.success_score, 0) / testOutcomes.data.length
      : 0;

    const effectSize = testMean - controlMean;
    const pooledSampleSize = controlOutcomes.data.length + testOutcomes.data.length;
    
    // Simplified statistical calculations
    const standardError = Math.sqrt((controlMean * (100 - controlMean) / controlOutcomes.data.length) + 
                                   (testMean * (100 - testMean) / testOutcomes.data.length));
    
    const zScore = standardError > 0 ? effectSize / standardError : 0;
    const pValue = Math.max(0.001, 1 - Math.abs(zScore) / 2); // Simplified p-value calculation
    
    const confidenceInterval: [number, number] = [
      effectSize - 1.96 * standardError,
      effectSize + 1.96 * standardError,
    ];

    const isSignificant = pValue < experiment.significance_level;
    const winner = effectSize > 0 ? 'test' : 'control';

    return {
      experiment,
      statistical_analysis: {
        p_value: pValue,
        confidence_interval: confidenceInterval,
        effect_size: effectSize,
        statistical_power: experiment.statistical_power,
      },
      recommendations: {
        winner: isSignificant ? winner : undefined,
        significance: isSignificant,
        next_steps: isSignificant 
          ? [`Implement ${winner} protocol`, 'Monitor performance', 'Plan rollout strategy']
          : ['Continue experiment', 'Increase sample size', 'Review protocol differences'],
      },
    };
  }

  // Evidence and Compliance Management
  async createProtocolEvidence(data: CreateProtocolEvidenceRequest): Promise<ProtocolEvidence> {
    const supabase = await createClient();
    const { data: result, error } = await supabase
      .from('protocol_evidence')
      .insert({
        ...data,
        created_by: (await supabase.auth.getUser()).data.user?.id,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) throw new Error(`Failed to create protocol evidence: ${error.message}`);
    return result;
  }

  async getProtocolEvidence(protocol_id: string): Promise<ProtocolEvidence[]> {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from('protocol_evidence')
      .select('*')
      .eq('protocol_id', protocol_id)
      .order('relevance_score', { ascending: false });

    if (error) throw new Error(`Failed to fetch protocol evidence: ${error.message}`);
    return data || [];
  }

  // Protocol Implementation and Distribution
  async createProtocolImplementation(data: CreateProtocolImplementationRequest): Promise<ProtocolImplementation> {
    const supabase = await createClient();
    const { data: result, error } = await supabase
      .from('protocol_implementations')
      .insert({
        ...data,
        implemented_by: (await supabase.auth.getUser()).data.user?.id,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) throw new Error(`Failed to create protocol implementation: ${error.message}`);
    return result;
  }

  async updateProtocolImplementation(id: string, data: UpdateProtocolImplementationRequest): Promise<ProtocolImplementation> {
    const supabase = await createClient();
    const { data: result, error } = await supabase
      .from('protocol_implementations')
      .update({
        ...data,
        updated_at: new Date().toISOString(),
      })
      .eq('id', id)
      .select()
      .single();

    if (error) throw new Error(`Failed to update protocol implementation: ${error.message}`);
    return result;
  }

  async getProtocolImplementations(protocol_version_id?: string): Promise<ProtocolImplementation[]> {
    let query = supabase.from('protocol_implementations').select('*');

    if (protocol_version_id) {
      query = query.eq('protocol_version_id', protocol_version_id);
    }

    const { data, error } = await query.order('created_at', { ascending: false });

    if (error) throw new Error(`Failed to fetch protocol implementations: ${error.message}`);
    return data || [];
  }

  // Analytics and Reporting
  async generateProtocolAnalytics(request: ProtocolAnalyticsRequest): Promise<ProtocolAnalytics> {
    const { protocol_version_id, analytics_period, period_start, period_end } = request;

    // Get outcomes for the specified period
    let outcomeQuery = supabase
      .from('protocol_outcomes')
      .select('*')
      .gte('outcome_date', period_start)
      .lte('outcome_date', period_end);

    if (protocol_version_id) {
      outcomeQuery = outcomeQuery.eq('protocol_version_id', protocol_version_id);
    }

    const { data: outcomes, error: outcomeError } = await outcomeQuery;

    if (outcomeError) throw new Error(`Failed to fetch outcomes for analytics: ${outcomeError.message}`);

    // Calculate analytics metrics
    const usageCount = outcomes?.length || 0;
    const successRate = usageCount > 0 
      ? outcomes!.reduce((sum, o) => sum + o.success_score, 0) / usageCount
      : 0;

    const averageOutcomeScore = successRate;
    const patientSatisfaction = outcomes?.filter(o => o.patient_satisfaction)
      .reduce((sum, o) => sum + (o.patient_satisfaction || 0), 0) / 
      (outcomes?.filter(o => o.patient_satisfaction).length || 1);

    const complicationRate = usageCount > 0 
      ? (outcomes!.filter(o => Array.isArray(o.complications) && o.complications.length > 0).length / usageCount) * 100
      : 0;

    // Create analytics record
    const analyticsData = {
      protocol_version_id: protocol_version_id || 'all_protocols',
      analytics_period,
      period_start,
      period_end,
      usage_count: usageCount,
      success_rate: successRate,
      average_outcome_score: averageOutcomeScore,
      patient_satisfaction: patientSatisfaction,
      complication_rate: complicationRate,
      performance_metrics: {
        total_treatments: usageCount,
        successful_treatments: outcomes?.filter(o => o.success_score >= 75).length || 0,
        complications: outcomes?.filter(o => Array.isArray(o.complications) && o.complications.length > 0).length || 0,
        side_effects: outcomes?.filter(o => Array.isArray(o.side_effects) && o.side_effects.length > 0).length || 0,
      },
      calculated_at: new Date().toISOString(),
      created_at: new Date().toISOString(),
    };

    const { data: result, error } = await supabase
      .from('protocol_analytics')
      .insert(analyticsData)
      .select()
      .single();

    if (error) throw new Error(`Failed to create protocol analytics: ${error.message}`);
    return result;
  }

  async generatePerformanceReport(protocol_version_id: string, period_start: string, period_end: string): Promise<ProtocolPerformanceReport> {
    const [protocol, analytics, outcomes, feedback] = await Promise.all([
      this.getProtocolVersionById(protocol_version_id),
      this.generateProtocolAnalytics({
        protocol_version_id,
        analytics_period: 'monthly',
        period_start,
        period_end,
      }),
      this.getProtocolOutcomes({ protocol_version_id }),
      this.getProtocolFeedback({ protocol_id: protocol_version_id }),
    ]);

    if (!protocol) {
      throw new Error('Protocol not found for performance report');
    }

    const report: ProtocolPerformanceReport = {
      protocol_version_id,
      reporting_period: {
        start: period_start,
        end: period_end,
      },
      key_metrics: {
        usage_count: analytics.usage_count,
        success_rate: analytics.success_rate || 0,
        patient_satisfaction: analytics.patient_satisfaction || 0,
        provider_satisfaction: feedback.data.filter(f => f.rating).reduce((sum, f) => sum + (f.rating || 0), 0) / 
          Math.max(1, feedback.data.filter(f => f.rating).length),
        cost_effectiveness: analytics.cost_effectiveness || 0,
      },
      trend_analysis: {
        success_trend: 'stable', // Simplified - would need historical data for real trends
        usage_trend: 'increasing',
        satisfaction_trend: 'stable',
      },
      benchmarks: {
        industry_average_success_rate: 75,
        clinic_average_success_rate: 80,
        target_success_rate: 85,
      },
      recommendations: [
        analytics.success_rate && analytics.success_rate < 75 
          ? 'Focus on improving success rate through protocol refinement'
          : 'Maintain current performance standards',
        feedback.data.length < 5 
          ? 'Encourage more provider feedback for continuous improvement'
          : 'Continue collecting structured feedback',
        analytics.usage_count < 20 
          ? 'Consider protocol promotion and training initiatives'
          : 'Monitor implementation consistency',
      ].filter(Boolean),
    };

    return report;
  }

  // Helper Methods
  private async processPriorityFeedback(feedback_id: string): Promise<void> {
    // Auto-escalate critical feedback
    const supabase = await createClient();
    await supabase
      .from('protocol_feedback')
      .update({
        status: 'reviewed',
        reviewed_at: new Date().toISOString(),
        implementation_notes: 'Auto-escalated due to priority level',
      })
      .eq('id', feedback_id);
  }

  async getProtocolOptimizationAnalysis(protocol_id: string): Promise<ProtocolOptimizationAnalysis> {
    const [protocol, outcomes, feedback, optimizationResults] = await Promise.all([
      this.getProtocolVersionById(protocol_id),
      this.getProtocolOutcomes({ protocol_version_id: protocol_id }),
      this.getProtocolFeedback({ protocol_id }),
      supabase.from('optimization_results').select('*').eq('protocol_id', protocol_id),
    ]);

    if (!protocol) {
      throw new Error('Protocol not found for optimization analysis');
    }

    const currentPerformance = {
      success_rate: outcomes.data.length > 0 
        ? outcomes.data.reduce((sum, o) => sum + o.success_score, 0) / outcomes.data.length
        : 0,
      total_outcomes: outcomes.data.length,
      feedback_score: feedback.data.filter(f => f.rating).reduce((sum, f) => sum + (f.rating || 0), 0) / 
        Math.max(1, feedback.data.filter(f => f.rating).length),
      complication_rate: outcomes.data.length > 0 
        ? (outcomes.data.filter(o => Array.isArray(o.complications) && o.complications.length > 0).length / outcomes.data.length) * 100
        : 0,
    };

    const optimizationOpportunities = [
      {
        type: 'success_rate_optimization',
        potential_improvement: Math.max(0, 85 - currentPerformance.success_rate),
        confidence_score: outcomes.data.length >= 10 ? 85 : 60,
        recommendation: currentPerformance.success_rate < 80 
          ? 'Focus on identifying and addressing low-performing protocol steps'
          : 'Fine-tune existing protocol for marginal improvements',
      },
      {
        type: 'complication_reduction',
        potential_improvement: Math.max(0, currentPerformance.complication_rate - 5),
        confidence_score: outcomes.data.length >= 20 ? 90 : 65,
        recommendation: currentPerformance.complication_rate > 10 
          ? 'Implement additional safety measures and risk mitigation strategies'
          : 'Maintain current safety standards with regular monitoring',
      },
    ].filter(opp => opp.potential_improvement > 0);

    return {
      protocol_id,
      current_performance: currentPerformance,
      optimization_opportunities: optimizationOpportunities,
      comparative_analysis: {
        peer_protocols: 'Analysis would include comparison with similar protocols',
        industry_benchmarks: 'Comparison with industry standards',
        historical_performance: 'Trends over time for this protocol',
      },
      risk_assessment: {
        implementation_risk: 'Low to Medium',
        patient_safety_risk: 'Low',
        operational_risk: 'Low',
        recommendations: [
          'Implement changes gradually',
          'Monitor outcomes closely',
          'Maintain rollback capability',
        ],
      },
    };
  }
}

