// API endpoint: GET /api/automated-protocol-optimization/protocols/[id]/optimization
// Story 9.3: Automated protocol optimization - Get protocol optimization analysis
// Generated by: VoidBeast V4.0

import { type NextRequest, NextResponse } from 'next/server';
import { AutomatedProtocolOptimizationService } from '../../../../../lib/services/automated-protocol-optimization';

const service = new AutomatedProtocolOptimizationService();

// GET: Get protocol optimization analysis
export async function GET(
  _request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params;

    if (!id) {
      return NextResponse.json(
        { success: false, error: 'Protocol ID is required' },
        { status: 400 }
      );
    }

    const optimizationAnalysis =
      await service.getProtocolOptimizationAnalysis(id);

    return NextResponse.json({
      success: true,
      data: optimizationAnalysis,
    });
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to fetch protocol optimization analysis',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
