// API endpoint: GET /api/automated-protocol-optimization/protocol-versions
// Story 9.3: Automated protocol optimization - Protocol version management
// Generated by: VoidBeast V4.0

import { NextRequest, NextResponse } from 'next/server';
import { AutomatedProtocolOptimizationService } from '../../../lib/services/automated-protocol-optimization';
import { 
  createProtocolVersionSchema,
  updateProtocolVersionSchema 
} from '../../../lib/validations/automated-protocol-optimization';

const service = new AutomatedProtocolOptimizationService();

// GET: List protocol versions with optional filters
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    
    const filters = {
      protocol_name: searchParams.get('protocol_name') || undefined,
      approval_status: searchParams.get('approval_status') || undefined,
      is_active: searchParams.get('is_active') ? searchParams.get('is_active') === 'true' : undefined,
      page: parseInt(searchParams.get('page') || '1'),
      per_page: parseInt(searchParams.get('per_page') || '20'),
    };

    const result = await service.getProtocolVersions(filters);

    return NextResponse.json({
      success: true,
      data: result.data,
      pagination: {
        page: filters.page,
        per_page: filters.per_page,
        total: result.total,
        total_pages: Math.ceil(result.total / filters.per_page),
      },
    });
  } catch (error) {
    console.error('Error fetching protocol versions:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to fetch protocol versions',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

// POST: Create new protocol version
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    // Validate request data
    const validation = createProtocolVersionSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { 
          success: false, 
          error: 'Validation failed',
          details: validation.error.format()
        },
        { status: 400 }
      );
    }

    const protocolVersion = await service.createProtocolVersion(validation.data);

    return NextResponse.json({
      success: true,
      data: protocolVersion,
      message: 'Protocol version created successfully'
    }, { status: 201 });
  } catch (error) {
    console.error('Error creating protocol version:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to create protocol version',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}
