# Ruler Configuration File
# See https://ai.intellectronica.net/ruler for documentation.

# Agents active by default when --agents is not used
default_agents = ["claude", "copilot", "cursor", "windsurf"]

# --- Agent Specific Configurations ---
[agents.claude]
enabled = true
output_path = "CLAUDE.md"

[agents.copilot]
enabled = true
output_path = ".github/copilot-instructions.md"

[agents.cursor]
enabled = true
output_path = ".cursor/rules/ruler_cursor_instructions.mdc"

[agents.windsurf]
enabled = true
output_path = ".windsurf/rules/ruler_windsurf_instructions.md"

[agents.aider]
enabled = true
output_path_instructions = "AGENTS.md"
output_path_config = ".aider.conf.yml"

[agents.cline]
enabled = true
output_path = ".clinerules"

# --- Global .gitignore Configuration ---
[gitignore]
enabled = true

# --- MCP Server Configuration (Examples - Commented) ---
# [mcp]
# enabled = true
# merge_strategy = "merge"

# [mcp_servers.example_stdio]
# command = "node"
# args = ["scripts/your-mcp-server.js"]
# env = { API_KEY = "replace_me" }

# [mcp_servers.example_remote]
# url = "https://api.example.com/mcp"
# headers = { Authorization = "Bearer REPLACE_ME" }