# Ruler Configuration File - NeonPro AI Healthcare Platform
# See https://ai.intellectronica.net/ruler for documentation.

# OPTIMIZED STRATEGY: Only APEX Healthcare Agents
# GitHub Copilot automatically loads claude, copilot, and trae configs
# Focus on specialized healthcare agents with contextual loading

# Default: claude agent (uses APEX healthcare configuration)
default_agents = ["claude"]

# --- Claude Agent with APEX Healthcare Configuration ---
[agents.claude]
enabled = true
output_path = ".claude/agents/apex-dev.md"
source_path = ".ruler/agents/apex-dev.md"
description = "APEX Healthcare Development with Constitutional Excellence"

# --- Global .gitignore Configuration ---
[gitignore]
enabled = true

# --- MCP Server Configuration (Examples - Commented) ---
# [mcp]
# enabled = true
# merge_strategy = "merge"

# [mcp_servers.example_stdio]
# command = "node"
# args = ["scripts/your-mcp-server.js"]
# env = { API_KEY = "replace_me" }

# [mcp_servers.example_remote]
# url = "https://api.example.com/mcp"
# headers = { Authorization = "Bearer REPLACE_ME" }
