// API endpoint: GET/POST /api/automated-protocol-optimization/outcomes
// Story 9.3: Automated protocol optimization - Protocol outcome tracking
// Generated by: VoidBeast V4.0

import { NextRequest, NextResponse } from 'next/server';
import { AutomatedProtocolOptimizationService } from '../../../lib/services/automated-protocol-optimization';
import { createProtocolOutcomeSchema } from '../../../lib/validations/automated-protocol-optimization';

const service = new AutomatedProtocolOptimizationService();

// GET: List protocol outcomes with optional filters
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    
    const filters = {
      protocol_version_id: searchParams.get('protocol_version_id') || undefined,
      patient_id: searchParams.get('patient_id') || undefined,
      success_score_min: searchParams.get('success_score_min') 
        ? parseInt(searchParams.get('success_score_min')!) 
        : undefined,
      success_score_max: searchParams.get('success_score_max') 
        ? parseInt(searchParams.get('success_score_max')!) 
        : undefined,
      page: parseInt(searchParams.get('page') || '1'),
      per_page: parseInt(searchParams.get('per_page') || '20'),
    };

    const result = await service.getProtocolOutcomes(filters);

    return NextResponse.json({
      success: true,
      data: result.data,
      pagination: {
        page: filters.page,
        per_page: filters.per_page,
        total: result.total,
        total_pages: Math.ceil(result.total / filters.per_page),
      },
    });
  } catch (error) {
    console.error('Error fetching protocol outcomes:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to fetch protocol outcomes',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

// POST: Create new protocol outcome
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    // Validate request data
    const validation = createProtocolOutcomeSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { 
          success: false, 
          error: 'Validation failed',
          details: validation.error.format()
        },
        { status: 400 }
      );
    }

    const protocolOutcome = await service.createProtocolOutcome(validation.data);

    return NextResponse.json({
      success: true,
      data: protocolOutcome,
      message: 'Protocol outcome recorded successfully'
    }, { status: 201 });
  } catch (error) {
    console.error('Error creating protocol outcome:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to record protocol outcome',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}