// API endpoint: POST /api/automated-protocol-optimization/reports
// Story 9.3: Automated protocol optimization - Generate performance reports
// Generated by: VoidBeast V4.0

import type { NextRequest } from "next/server";

const service = new AutomatedProtocolOptimizationService();

const performanceReportSchema = z.object({
  protocol_version_id: z.string().uuid("Protocol version ID must be a valid UUID"),
  period_start: z.string().datetime("Invalid start date format"),
  period_end: z.string().datetime("Invalid end date format"),
});

// POST: Generate performance report
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    // Validate request data
    const validation = performanceReportSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        {
          success: false,
          error: "Validation failed",
          details: validation.error.format(),
        },
        { status: 400 },
      );
    }

    const { protocol_version_id, period_start, period_end } = validation.data;

    const performanceReport = await service.generatePerformanceReport(
      protocol_version_id,
      period_start,
      period_end,
    );

    return NextResponse.json({
      success: true,
      data: performanceReport,
      message: "Performance report generated successfully",
    });
  } catch (error) {
    console.error("Error generating performance report:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to generate performance report",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}
