// AR Simulator Constants and Types

const VALIDATION_LIMITS = {
  MAX_PRIORITY: 5,
  MAX_SESSIONS: 10,
  MAX_SEVERITY: 10,
  MAX_SIMULATIONS_COMPARE: 5,
  MIN_PRIORITY: 1,
  MIN_SESSIONS: 1,
  MIN_SEVERITY: 1,
  MIN_SIMULATIONS_COMPARE: 2,
  PATIENT_ID_MIN_LENGTH: 1,
} as const;

const HTTP_STATUS = {
  BAD_REQUEST: 400,
  INTERNAL_SERVER_ERROR: 500,
  NOT_FOUND: 404,
  OK: 200,
} as const;

export { HTTP_STATUS, VALIDATION_LIMITS };
