// Analytics Export Dashboard Component - STORY-SUB-002 Task 7
// Created: 2025-01-22
// Comprehensive export interface with real-time progress tracking

'use client';

import { format, subDays } from 'date-fns';
import {
  AlertCircle,
  BarChart3,
  Calendar as CalendarIcon,
  CheckCircle,
  Clock,
  DollarSign,
  Download,
  Eye,
  FileImage,
  FileSpreadsheet,
  FileText,
  Loader2,
  Settings,
  Target,
  Trash2,
  TrendingUp,
  Users,
  XCircle,
  Zap,
} from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import { Progress } from '@/components/ui/progress';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import type {
  CSVExportOptions,
  ExcelExportOptions,
  ExportConfig,
  ExportFormat,
  ExportRequest,
  ExportResponse,
  PDFExportOptions,
  ReportType,
} from '@/lib/analytics/export/types';
import { cn } from '@/lib/utils';

// ============================================================================
// TYPES AND INTERFACES
// ============================================================================

type ExportDashboardProps = {
  className?: string;
  defaultDateRange?: {
    startDate: Date;
    endDate: Date;
  };
  onExportComplete?: (response: ExportResponse) => void;
  onExportError?: (error: any) => void;
};

type ActiveExport = {
  id: string;
  config: ExportConfig;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
  progress?: {
    percentage: number;
    currentStep: string;
    estimatedTimeRemaining?: number;
  };
  createdAt: Date;
  completedAt?: Date;
  downloadUrl?: string;
  fileName?: string;
  fileSize?: number;
  error?: {
    code: string;
    message: string;
  };
};

type ExportFormData = {
  format: ExportFormat;
  reportType: ReportType;
  dateRange: {
    startDate: Date;
    endDate: Date;
  };
  filters: Record<string, any>;
  includeSummary: boolean;
  customization: {
    title?: string;
    subtitle?: string;
    logo?: string;
    branding?: {
      primaryColor?: string;
      secondaryColor?: string;
      fontFamily?: string;
    };
  };
  pdfOptions: PDFExportOptions;
  excelOptions: ExcelExportOptions;
  csvOptions: CSVExportOptions;
  notifyOnComplete: boolean;
  email?: string;
};

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export function ExportDashboard({
  className,
  defaultDateRange = {
    startDate: subDays(new Date(), 30),
    endDate: new Date(),
  },
  onExportComplete,
  onExportError,
}: ExportDashboardProps) {
  // State management
  const [activeTab, setActiveTab] = useState<'create' | 'history'>('create');
  const [isLoading, setIsLoading] = useState(false);
  const [activeExports, setActiveExports] = useState<ActiveExport[]>([]);
  const [exportHistory, setExportHistory] = useState<ActiveExport[]>([]);

  // Form state
  const [formData, setFormData] = useState<ExportFormData>({
    format: 'pdf',
    reportType: 'comprehensive',
    dateRange: defaultDateRange,
    filters: {},
    includeSummary: true,
    customization: {
      title: 'Analytics Report',
      subtitle: 'Generated by NeonPro Analytics',
      branding: {
        primaryColor: '#1f2937',
        secondaryColor: '#6b7280',
        fontFamily: 'Inter',
      },
    },
    pdfOptions: {
      orientation: 'portrait',
      pageSize: 'A4',
      margins: { top: 20, right: 20, bottom: 20, left: 20 },
      styling: {
        fontFamily: 'helvetica',
        fontSize: 12,
        primaryColor: '#1f2937',
        secondaryColor: '#6b7280',
      },
      header: {
        text: 'NeonPro Analytics Report',
        fontSize: 16,
        alignment: 'center',
      },
      footer: {
        includePageNumbers: true,
        includeTimestamp: true,
      },
    },
    excelOptions: {
      worksheets: {
        summary: true,
        revenue: true,
        conversion: true,
        cohorts: true,
        forecasts: true,
        rawData: false,
      },
      formatting: {
        autoWidth: true,
        freezeHeaders: true,
        alternatingRows: true,
        numberFormat: '#,##0.00',
      },
    },
    csvOptions: {
      delimiter: ',',
      encoding: 'utf8',
      includeHeaders: true,
      compression: 'none',
    },
    notifyOnComplete: false,
  });

  // ========================================================================
  // EFFECTS
  // ========================================================================

  useEffect(() => {
    loadExportHistory();
    const interval = setInterval(pollActiveExports, 2000);
    return () => clearInterval(interval);
  }, [loadExportHistory, pollActiveExports]);

  // ========================================================================
  // API FUNCTIONS
  // ========================================================================

  const createExport = useCallback(async () => {
    setIsLoading(true);

    try {
      const exportRequest: Omit<
        ExportRequest,
        'id' | 'userId' | 'createdAt' | 'priority'
      > = {
        config: {
          format: formData.format,
          reportType: formData.reportType,
          dateRange: formData.dateRange,
          filters: formData.filters,
          includeSummary: formData.includeSummary,
          customization: formData.customization,
        },
        pdfOptions: formData.pdfOptions,
        excelOptions: formData.excelOptions,
        csvOptions: formData.csvOptions,
        notifyOnComplete: formData.notifyOnComplete,
        email: formData.notifyOnComplete ? formData.email : undefined,
      };

      const response = await fetch('/api/analytics/export', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(exportRequest),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error?.message || 'Export request failed');
      }

      const result = await response.json();

      // Add to active exports
      const newExport: ActiveExport = {
        id: result.id,
        config: exportRequest.config,
        status: 'pending',
        createdAt: new Date(),
      };

      setActiveExports((prev) => [newExport, ...prev]);
      setActiveTab('history');

      toast.success('Export request created successfully', {
        description: `Estimated completion time: ${result.estimatedCompletionTime} seconds`,
      });
    } catch (error) {
      toast.error('Failed to create export', {
        description:
          error instanceof Error ? error.message : 'Unknown error occurred',
      });
      onExportError?.(error);
    } finally {
      setIsLoading(false);
    }
  }, [formData, onExportError]);

  const pollActiveExports = useCallback(async () => {
    if (activeExports.length === 0) {
      return;
    }

    const pendingExports = activeExports.filter(
      (exp) => exp.status === 'pending' || exp.status === 'processing',
    );

    if (pendingExports.length === 0) {
      return;
    }

    try {
      const statusPromises = pendingExports.map(async (exp) => {
        const response = await fetch(`/api/analytics/export/${exp.id}`);
        if (response.ok) {
          return await response.json();
        }
        return null;
      });

      const statuses = await Promise.all(statusPromises);

      setActiveExports((prev) =>
        prev.map((exp) => {
          const statusIndex = pendingExports.findIndex(
            (pending) => pending.id === exp.id,
          );
          if (statusIndex >= 0 && statuses[statusIndex]) {
            const status = statuses[statusIndex];
            const updatedExport = {
              ...exp,
              status: status.status,
              progress: status.progress,
              downloadUrl: status.downloadUrl,
              fileName: status.fileName,
              fileSize: status.fileSize,
              completedAt: status.completedAt
                ? new Date(status.completedAt)
                : undefined,
              error: status.error,
            };

            // Notify on completion
            if (status.status === 'completed' && exp.status !== 'completed') {
              toast.success('Export completed successfully', {
                description: `${status.fileName} is ready for download`,
              });
              onExportComplete?.(status);
            } else if (status.status === 'failed' && exp.status !== 'failed') {
              toast.error('Export failed', {
                description: status.error?.message || 'Unknown error occurred',
              });
            }

            return updatedExport;
          }
          return exp;
        }),
      );
    } catch (_error) {}
  }, [activeExports, onExportComplete]);

  const loadExportHistory = useCallback(async () => {
    try {
      // This would typically load from a user exports endpoint
      // For now, we'll use localStorage as a simple cache
      const cached = localStorage.getItem('export-history');
      if (cached) {
        const history = JSON.parse(cached);
        setExportHistory(
          history.map((item: any) => ({
            ...item,
            createdAt: new Date(item.createdAt),
            completedAt: item.completedAt
              ? new Date(item.completedAt)
              : undefined,
          })),
        );
      }
    } catch (_error) {}
  }, []);

  const cancelExport = useCallback(async (exportId: string) => {
    try {
      const response = await fetch(`/api/analytics/export/${exportId}`, {
        method: 'DELETE',
      });

      if (response.ok) {
        setActiveExports((prev) =>
          prev.map((exp) =>
            exp.id === exportId
              ? { ...exp, status: 'cancelled' as const }
              : exp,
          ),
        );
        toast.success('Export cancelled successfully');
      }
    } catch (_error) {
      toast.error('Failed to cancel export');
    }
  }, []);

  const downloadExport = useCallback(async (exportItem: ActiveExport) => {
    if (!exportItem.downloadUrl) {
      return;
    }

    try {
      const link = document.createElement('a');
      link.href = exportItem.downloadUrl;
      link.download = exportItem.fileName || 'export';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      toast.success('Download started');
    } catch (_error) {
      toast.error('Failed to download file');
    }
  }, []);

  // ========================================================================
  // FORM HANDLERS
  // ========================================================================

  const updateFormData = useCallback((updates: Partial<ExportFormData>) => {
    setFormData((prev) => ({ ...prev, ...updates }));
  }, []);

  const updateNestedFormData = useCallback((path: string, value: any) => {
    setFormData((prev) => {
      const newData = { ...prev };
      const keys = path.split('.');
      let current: any = newData;

      for (let i = 0; i < keys.length - 1; i++) {
        if (!(keys[i] in current)) {
          current[keys[i]] = {};
        }
        current = current[keys[i]];
      }

      current[keys.at(-1)] = value;
      return newData;
    });
  }, []);

  // ========================================================================
  // RENDER HELPERS
  // ========================================================================

  const getFormatIcon = (format: ExportFormat) => {
    switch (format) {
      case 'pdf':
        return <FileText className="h-4 w-4" />;
      case 'excel':
        return <FileSpreadsheet className="h-4 w-4" />;
      case 'csv':
        return <FileText className="h-4 w-4" />;
      case 'json':
        return <FileText className="h-4 w-4" />;
      default:
        return <FileText className="h-4 w-4" />;
    }
  };

  const getReportTypeIcon = (reportType: ReportType) => {
    switch (reportType) {
      case 'revenue':
        return <DollarSign className="h-4 w-4" />;
      case 'conversion':
        return <Target className="h-4 w-4" />;
      case 'trial':
        return <Zap className="h-4 w-4" />;
      case 'cohort':
        return <Users className="h-4 w-4" />;
      case 'forecast':
        return <TrendingUp className="h-4 w-4" />;
      case 'comprehensive':
        return <BarChart3 className="h-4 w-4" />;
      default:
        return <BarChart3 className="h-4 w-4" />;
    }
  };

  const getStatusIcon = (status: ActiveExport['status']) => {
    switch (status) {
      case 'pending':
        return <Clock className="h-4 w-4 text-yellow-500" />;
      case 'processing':
        return <Loader2 className="h-4 w-4 animate-spin text-blue-500" />;
      case 'completed':
        return <CheckCircle className="h-4 w-4 text-green-500" />;
      case 'failed':
        return <XCircle className="h-4 w-4 text-red-500" />;
      case 'cancelled':
        return <AlertCircle className="h-4 w-4 text-gray-500" />;
      default:
        return <Clock className="h-4 w-4" />;
    }
  };

  const getStatusBadgeVariant = (status: ActiveExport['status']) => {
    switch (status) {
      case 'pending':
        return 'secondary';
      case 'processing':
        return 'default';
      case 'completed':
        return 'default';
      case 'failed':
        return 'destructive';
      case 'cancelled':
        return 'outline';
      default:
        return 'secondary';
    }
  };

  const formatFileSize = (bytes?: number) => {
    if (!bytes) {
      return 'Unknown';
    }
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(1024));
    return `${Math.round((bytes / 1024 ** i) * 100) / 100} ${sizes[i]}`;
  };

  const formatDuration = (ms?: number) => {
    if (!ms) {
      return 'Unknown';
    }
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);

    if (hours > 0) {
      return `${hours}h ${minutes % 60}m`;
    }
    if (minutes > 0) {
      return `${minutes}m ${seconds % 60}s`;
    }
    return `${seconds}s`;
  };

  // ========================================================================
  // RENDER
  // ========================================================================

  return (
    <div className={cn('space-y-6', className)}>
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="font-bold text-2xl tracking-tight">
            Analytics Export
          </h2>
          <p className="text-muted-foreground">
            Export your analytics data in multiple formats with customizable
            options
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Badge className="text-xs" variant="outline">
            {activeExports.filter((exp) => exp.status === 'processing').length}{' '}
            Processing
          </Badge>
          <Badge className="text-xs" variant="outline">
            {activeExports.filter((exp) => exp.status === 'completed').length}{' '}
            Completed
          </Badge>
        </div>
      </div>

      {/* Main Content */}
      <Tabs
        onValueChange={(value) => setActiveTab(value as 'create' | 'history')}
        value={activeTab}
      >
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger className="flex items-center gap-2" value="create">
            <Download className="h-4 w-4" />
            Create Export
          </TabsTrigger>
          <TabsTrigger className="flex items-center gap-2" value="history">
            <Clock className="h-4 w-4" />
            Export History
          </TabsTrigger>
        </TabsList>

        {/* Create Export Tab */}
        <TabsContent className="space-y-6" value="create">
          <div className="grid gap-6 lg:grid-cols-3">
            {/* Export Configuration */}
            <div className="space-y-6 lg:col-span-2">
              {/* Basic Configuration */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Settings className="h-5 w-5" />
                    Export Configuration
                  </CardTitle>
                  <CardDescription>
                    Configure the basic settings for your export
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid gap-4 md:grid-cols-2">
                    {/* Format Selection */}
                    <div className="space-y-2">
                      <Label htmlFor="format">Export Format</Label>
                      <Select
                        onValueChange={(value: ExportFormat) =>
                          updateFormData({ format: value })
                        }
                        value={formData.format}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select format" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="pdf">
                            <div className="flex items-center gap-2">
                              <FileText className="h-4 w-4" />
                              PDF Report
                            </div>
                          </SelectItem>
                          <SelectItem value="excel">
                            <div className="flex items-center gap-2">
                              <FileSpreadsheet className="h-4 w-4" />
                              Excel Workbook
                            </div>
                          </SelectItem>
                          <SelectItem value="csv">
                            <div className="flex items-center gap-2">
                              <FileText className="h-4 w-4" />
                              CSV Data
                            </div>
                          </SelectItem>
                          <SelectItem value="json">
                            <div className="flex items-center gap-2">
                              <FileText className="h-4 w-4" />
                              JSON Data
                            </div>
                          </SelectItem>
                        </SelectContent>
                      </Select>
                    </div>

                    {/* Report Type Selection */}
                    <div className="space-y-2">
                      <Label htmlFor="reportType">Report Type</Label>
                      <Select
                        onValueChange={(value: ReportType) =>
                          updateFormData({ reportType: value })
                        }
                        value={formData.reportType}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select report type" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="revenue">
                            <div className="flex items-center gap-2">
                              <DollarSign className="h-4 w-4" />
                              Revenue Analytics
                            </div>
                          </SelectItem>
                          <SelectItem value="conversion">
                            <div className="flex items-center gap-2">
                              <Target className="h-4 w-4" />
                              Conversion Metrics
                            </div>
                          </SelectItem>
                          <SelectItem value="trial">
                            <div className="flex items-center gap-2">
                              <Zap className="h-4 w-4" />
                              Trial Analytics
                            </div>
                          </SelectItem>
                          <SelectItem value="cohort">
                            <div className="flex items-center gap-2">
                              <Users className="h-4 w-4" />
                              Cohort Analysis
                            </div>
                          </SelectItem>
                          <SelectItem value="forecast">
                            <div className="flex items-center gap-2">
                              <TrendingUp className="h-4 w-4" />
                              Revenue Forecasts
                            </div>
                          </SelectItem>
                          <SelectItem value="comprehensive">
                            <div className="flex items-center gap-2">
                              <BarChart3 className="h-4 w-4" />
                              Comprehensive Report
                            </div>
                          </SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>

                  {/* Date Range */}
                  <div className="space-y-2">
                    <Label>Date Range</Label>
                    <div className="grid gap-2 md:grid-cols-2">
                      <Popover>
                        <PopoverTrigger asChild>
                          <Button
                            className={cn(
                              'justify-start text-left font-normal',
                              !formData.dateRange.startDate &&
                                'text-muted-foreground',
                            )}
                            variant="outline"
                          >
                            <CalendarIcon className="mr-2 h-4 w-4" />
                            {formData.dateRange.startDate ? (
                              format(formData.dateRange.startDate, 'PPP')
                            ) : (
                              <span>Pick start date</span>
                            )}
                          </Button>
                        </PopoverTrigger>
                        <PopoverContent className="w-auto p-0">
                          <Calendar
                            initialFocus
                            mode="single"
                            onSelect={(date) =>
                              date &&
                              updateNestedFormData('dateRange.startDate', date)
                            }
                            selected={formData.dateRange.startDate}
                          />
                        </PopoverContent>
                      </Popover>

                      <Popover>
                        <PopoverTrigger asChild>
                          <Button
                            className={cn(
                              'justify-start text-left font-normal',
                              !formData.dateRange.endDate &&
                                'text-muted-foreground',
                            )}
                            variant="outline"
                          >
                            <CalendarIcon className="mr-2 h-4 w-4" />
                            {formData.dateRange.endDate ? (
                              format(formData.dateRange.endDate, 'PPP')
                            ) : (
                              <span>Pick end date</span>
                            )}
                          </Button>
                        </PopoverTrigger>
                        <PopoverContent className="w-auto p-0">
                          <Calendar
                            initialFocus
                            mode="single"
                            onSelect={(date) =>
                              date &&
                              updateNestedFormData('dateRange.endDate', date)
                            }
                            selected={formData.dateRange.endDate}
                          />
                        </PopoverContent>
                      </Popover>
                    </div>
                  </div>

                  {/* Options */}
                  <div className="space-y-3">
                    <div className="flex items-center space-x-2">
                      <Checkbox
                        checked={formData.includeSummary}
                        id="includeSummary"
                        onCheckedChange={(checked) =>
                          updateFormData({ includeSummary: Boolean(checked) })
                        }
                      />
                      <Label htmlFor="includeSummary">
                        Include executive summary
                      </Label>
                    </div>

                    <div className="flex items-center space-x-2">
                      <Checkbox
                        checked={formData.notifyOnComplete}
                        id="notifyOnComplete"
                        onCheckedChange={(checked) =>
                          updateFormData({ notifyOnComplete: Boolean(checked) })
                        }
                      />
                      <Label htmlFor="notifyOnComplete">
                        Email notification when complete
                      </Label>
                    </div>

                    {formData.notifyOnComplete && (
                      <div className="space-y-2">
                        <Label htmlFor="email">Email Address</Label>
                        <Input
                          id="email"
                          onChange={(e) =>
                            updateFormData({ email: e.target.value })
                          }
                          placeholder="your@email.com"
                          type="email"
                          value={formData.email || ''}
                        />
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Customization */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <FileImage className="h-5 w-5" />
                    Customization
                  </CardTitle>
                  <CardDescription>
                    Customize the appearance and branding of your export
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid gap-4 md:grid-cols-2">
                    <div className="space-y-2">
                      <Label htmlFor="title">Report Title</Label>
                      <Input
                        id="title"
                        onChange={(e) =>
                          updateNestedFormData(
                            'customization.title',
                            e.target.value,
                          )
                        }
                        placeholder="Analytics Report"
                        value={formData.customization.title || ''}
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="subtitle">Report Subtitle</Label>
                      <Input
                        id="subtitle"
                        onChange={(e) =>
                          updateNestedFormData(
                            'customization.subtitle',
                            e.target.value,
                          )
                        }
                        placeholder="Generated by NeonPro Analytics"
                        value={formData.customization.subtitle || ''}
                      />
                    </div>
                  </div>

                  <div className="grid gap-4 md:grid-cols-3">
                    <div className="space-y-2">
                      <Label htmlFor="primaryColor">Primary Color</Label>
                      <Input
                        id="primaryColor"
                        onChange={(e) =>
                          updateNestedFormData(
                            'customization.branding.primaryColor',
                            e.target.value,
                          )
                        }
                        type="color"
                        value={
                          formData.customization.branding?.primaryColor ||
                          '#1f2937'
                        }
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="secondaryColor">Secondary Color</Label>
                      <Input
                        id="secondaryColor"
                        onChange={(e) =>
                          updateNestedFormData(
                            'customization.branding.secondaryColor',
                            e.target.value,
                          )
                        }
                        type="color"
                        value={
                          formData.customization.branding?.secondaryColor ||
                          '#6b7280'
                        }
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="fontFamily">Font Family</Label>
                      <Select
                        onValueChange={(value) =>
                          updateNestedFormData(
                            'customization.branding.fontFamily',
                            value,
                          )
                        }
                        value={
                          formData.customization.branding?.fontFamily || 'Inter'
                        }
                      >
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="Inter">Inter</SelectItem>
                          <SelectItem value="Roboto">Roboto</SelectItem>
                          <SelectItem value="Open Sans">Open Sans</SelectItem>
                          <SelectItem value="Lato">Lato</SelectItem>
                          <SelectItem value="Montserrat">Montserrat</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Preview and Actions */}
            <div className="space-y-6">
              {/* Export Preview */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Eye className="h-5 w-5" />
                    Export Preview
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <div className="flex items-center gap-2 text-sm">
                      {getFormatIcon(formData.format)}
                      <span className="font-medium">
                        {formData.format.toUpperCase()}
                      </span>
                    </div>

                    <div className="flex items-center gap-2 text-muted-foreground text-sm">
                      {getReportTypeIcon(formData.reportType)}
                      <span>
                        {formData.reportType.charAt(0).toUpperCase() +
                          formData.reportType.slice(1)}{' '}
                        Report
                      </span>
                    </div>

                    <div className="text-muted-foreground text-sm">
                      {format(formData.dateRange.startDate, 'MMM d, yyyy')} -{' '}
                      {format(formData.dateRange.endDate, 'MMM d, yyyy')}
                    </div>
                  </div>

                  <Separator />

                  <div className="space-y-2 text-muted-foreground text-xs">
                    <div>
                      Title:{' '}
                      {formData.customization.title || 'Analytics Report'}
                    </div>
                    <div>
                      Subtitle:{' '}
                      {formData.customization.subtitle ||
                        'Generated by NeonPro Analytics'}
                    </div>
                    <div>
                      Summary:{' '}
                      {formData.includeSummary ? 'Included' : 'Not included'}
                    </div>
                    <div>
                      Notification:{' '}
                      {formData.notifyOnComplete ? 'Enabled' : 'Disabled'}
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Actions */}
              <Card>
                <CardContent className="pt-6">
                  <Button
                    className="w-full"
                    disabled={isLoading}
                    onClick={createExport}
                    size="lg"
                  >
                    {isLoading ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Creating Export...
                      </>
                    ) : (
                      <>
                        <Download className="mr-2 h-4 w-4" />
                        Create Export
                      </>
                    )}
                  </Button>
                </CardContent>
              </Card>

              {/* Quick Actions */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-sm">Quick Actions</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  <Button
                    className="w-full justify-start"
                    onClick={() => {
                      updateFormData({
                        format: 'pdf',
                        reportType: 'comprehensive',
                        dateRange: {
                          startDate: subDays(new Date(), 30),
                          endDate: new Date(),
                        },
                      });
                    }}
                    size="sm"
                    variant="outline"
                  >
                    <FileText className="mr-2 h-4 w-4" />
                    Monthly PDF Report
                  </Button>

                  <Button
                    className="w-full justify-start"
                    onClick={() => {
                      updateFormData({
                        format: 'excel',
                        reportType: 'revenue',
                        dateRange: {
                          startDate: subDays(new Date(), 90),
                          endDate: new Date(),
                        },
                      });
                    }}
                    size="sm"
                    variant="outline"
                  >
                    <FileSpreadsheet className="mr-2 h-4 w-4" />
                    Quarterly Excel
                  </Button>

                  <Button
                    className="w-full justify-start"
                    onClick={() => {
                      updateFormData({
                        format: 'csv',
                        reportType: 'cohort',
                        dateRange: {
                          startDate: subDays(new Date(), 7),
                          endDate: new Date(),
                        },
                      });
                    }}
                    size="sm"
                    variant="outline"
                  >
                    <FileText className="mr-2 h-4 w-4" />
                    Weekly CSV Data
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </TabsContent>

        {/* Export History Tab */}
        <TabsContent className="space-y-6" value="history">
          {/* Active Exports */}
          {activeExports.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Loader2 className="h-5 w-5" />
                  Active Exports
                </CardTitle>
                <CardDescription>Currently processing exports</CardDescription>
              </CardHeader>
              <CardContent>
                <ScrollArea className="h-[300px]">
                  <div className="space-y-4">
                    {activeExports.map((exportItem) => (
                      <div
                        className="flex items-center justify-between rounded-lg border p-4"
                        key={exportItem.id}
                      >
                        <div className="flex items-center gap-3">
                          {getFormatIcon(exportItem.config.format)}
                          <div>
                            <div className="font-medium">
                              {exportItem.config.reportType
                                .charAt(0)
                                .toUpperCase() +
                                exportItem.config.reportType.slice(1)}{' '}
                              Report
                            </div>
                            <div className="text-muted-foreground text-sm">
                              {exportItem.config.format.toUpperCase()} •{' '}
                              {format(exportItem.createdAt, 'MMM d, HH:mm')}
                            </div>
                            {exportItem.progress &&
                              exportItem.status === 'processing' && (
                                <div className="mt-2 space-y-1">
                                  <div className="flex items-center justify-between text-xs">
                                    <span>
                                      {exportItem.progress.currentStep}
                                    </span>
                                    <span>
                                      {exportItem.progress.percentage}%
                                    </span>
                                  </div>
                                  <Progress
                                    className="h-1"
                                    value={exportItem.progress.percentage}
                                  />
                                  {exportItem.progress
                                    .estimatedTimeRemaining && (
                                    <div className="text-muted-foreground text-xs">
                                      ~
                                      {formatDuration(
                                        exportItem.progress
                                          .estimatedTimeRemaining,
                                      )}{' '}
                                      remaining
                                    </div>
                                  )}
                                </div>
                              )}
                          </div>
                        </div>

                        <div className="flex items-center gap-2">
                          <Badge
                            variant={getStatusBadgeVariant(exportItem.status)}
                          >
                            <div className="flex items-center gap-1">
                              {getStatusIcon(exportItem.status)}
                              {exportItem.status}
                            </div>
                          </Badge>

                          {exportItem.status === 'completed' &&
                            exportItem.downloadUrl && (
                              <Button
                                onClick={() => downloadExport(exportItem)}
                                size="sm"
                              >
                                <Download className="h-4 w-4" />
                              </Button>
                            )}

                          {(exportItem.status === 'pending' ||
                            exportItem.status === 'processing') && (
                            <Button
                              onClick={() => cancelExport(exportItem.id)}
                              size="sm"
                              variant="outline"
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </ScrollArea>
              </CardContent>
            </Card>
          )}

          {/* Export History */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Clock className="h-5 w-5" />
                Export History
              </CardTitle>
              <CardDescription>Previous exports and downloads</CardDescription>
            </CardHeader>
            <CardContent>
              {exportHistory.length === 0 ? (
                <div className="py-8 text-center text-muted-foreground">
                  <FileText className="mx-auto mb-4 h-12 w-12 opacity-50" />
                  <p>No export history yet</p>
                  <p className="text-sm">
                    Create your first export to see it here
                  </p>
                </div>
              ) : (
                <ScrollArea className="h-[400px]">
                  <div className="space-y-4">
                    {exportHistory.map((exportItem) => (
                      <div
                        className="flex items-center justify-between rounded-lg border p-4"
                        key={exportItem.id}
                      >
                        <div className="flex items-center gap-3">
                          {getFormatIcon(exportItem.config.format)}
                          <div>
                            <div className="font-medium">
                              {exportItem.fileName ||
                                `${exportItem.config.reportType}-export`}
                            </div>
                            <div className="text-muted-foreground text-sm">
                              {exportItem.config.format.toUpperCase()} •{' '}
                              {formatFileSize(exportItem.fileSize)} •{' '}
                              {format(
                                exportItem.createdAt,
                                'MMM d, yyyy HH:mm',
                              )}
                            </div>
                            {exportItem.completedAt && (
                              <div className="text-muted-foreground text-xs">
                                Completed in{' '}
                                {formatDuration(
                                  exportItem.completedAt.getTime() -
                                    exportItem.createdAt.getTime(),
                                )}
                              </div>
                            )}
                          </div>
                        </div>

                        <div className="flex items-center gap-2">
                          <Badge
                            variant={getStatusBadgeVariant(exportItem.status)}
                          >
                            <div className="flex items-center gap-1">
                              {getStatusIcon(exportItem.status)}
                              {exportItem.status}
                            </div>
                          </Badge>

                          {exportItem.status === 'completed' &&
                            exportItem.downloadUrl && (
                              <Button
                                onClick={() => downloadExport(exportItem)}
                                size="sm"
                                variant="outline"
                              >
                                <Download className="h-4 w-4" />
                              </Button>
                            )}
                        </div>
                      </div>
                    ))}
                  </div>
                </ScrollArea>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}

export default ExportDashboard;
