import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: false,
  sourcemap: false,
  clean: true,
  external: [
    'react',
    'react-dom',
    'framer-motion',
    '@radix-ui/react-slot',
    'lucide-react',
    'class-variance-authority',
    'clsx',
    'tailwind-merge',
    '@radix-ui/react-accordion',
    '@radix-ui/react-alert-dialog',
    '@radix-ui/react-avatar',
    '@radix-ui/react-checkbox',
    '@radix-ui/react-dialog',
    '@radix-ui/react-dropdown-menu',
    '@radix-ui/react-label',
    '@radix-ui/react-navigation-menu',
    '@radix-ui/react-popover',
    '@radix-ui/react-progress',
    '@radix-ui/react-radio-group',
    '@radix-ui/react-scroll-area',
    '@radix-ui/react-select',
    '@radix-ui/react-separator',
    '@radix-ui/react-switch',
    '@radix-ui/react-tabs',
    '@radix-ui/react-toast',
    'react-day-picker',
    'date-fns',
    'cmdk',
    'input-otp',
    'react-resizable-panels',
    'vaul',
    '@/utils',
    '@/types',
    '@/components',
  ],
  treeshake: true,
  skipNodeModulesBundle: true,
})
