// API endpoint: POST /api/automated-protocol-optimization/analytics
// Story 9.3: Automated protocol optimization - Generate protocol analytics
// Generated by: VoidBeast V4.0

import type { NextRequest } from "next/server";

const service = new AutomatedProtocolOptimizationService();

// POST: Generate protocol analytics
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    // Validate request data
    const validation = ProtocolAnalyticsRequestSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        {
          success: false,
          error: "Validation failed",
          details: validation.error.format(),
        },
        { status: 400 },
      );
    }

    const analytics = await service.generateProtocolAnalytics(validation.data);

    return NextResponse.json({
      success: true,
      data: analytics,
      message: "Protocol analytics generated successfully",
    });
  } catch (error) {
    console.error("Error generating protocol analytics:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to generate protocol analytics",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}
