// API endpoint: PUT /api/automated-protocol-optimization/feedback/[id]
// Story 9.3: Automated protocol optimization - Update protocol feedback
// Generated by: VoidBeast V4.0

import { type NextRequest, NextResponse } from 'next/server';
import { AutomatedProtocolOptimizationService } from '../../../../lib/services/automated-protocol-optimization';
import { updateProtocolFeedbackSchema } from '../../../../lib/validations/automated-protocol-optimization';

const service = new AutomatedProtocolOptimizationService();

// PUT: Update protocol feedback
export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params;
    const body = await request.json();

    if (!id) {
      return NextResponse.json(
        { success: false, error: 'Feedback ID is required' },
        { status: 400 }
      );
    }

    // Validate request data
    const validation = updateProtocolFeedbackSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        {
          success: false,
          error: 'Validation failed',
          details: validation.error.format(),
        },
        { status: 400 }
      );
    }

    const updatedFeedback = await service.updateProtocolFeedback(
      id,
      validation.data
    );

    return NextResponse.json({
      success: true,
      data: updatedFeedback,
      message: 'Protocol feedback updated successfully',
    });
  } catch (error) {
    console.error('Error updating protocol feedback:', error);
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to update protocol feedback',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
