# CodeRabbit Configuration for NeonPro Healthcare Platform

# Language and framework settings
language: "en"
framework: "next.js"

# Review settings
reviews:
  # Enable automatic reviews
  auto_review:
    enabled: true

  # Review depth
  review_level: "thorough"

  # Focus areas for healthcare compliance
  review_focus:
    - "security"
    - "performance"
    - "accessibility"
    - "data_privacy"
    - "error_handling"
    - "logging"
    - "validation"

  # Healthcare-specific checks
  healthcare_compliance:
    lgpd: true
    anvisa: true
    cfm: true
    hipaa: false # Not applicable for Brazilian healthcare

  # Code quality thresholds
  code_quality:
    complexity_threshold: 10
    test_coverage_threshold: 80
    security_score_threshold: 8

# File patterns to review
include_patterns:
  - "apps/**/*.{ts,tsx,js,jsx}"
  - "packages/**/*.{ts,tsx,js,jsx}"
  - "libs/**/*.{ts,tsx,js,jsx}"
  - "**/*.sql"
  - "**/*.prisma"
  - "**/Dockerfile*"
  - "**/*.yml"
  - "**/*.yaml"

# File patterns to exclude
exclude_patterns:
  - "**/*.test.{ts,tsx,js,jsx}"
  - "**/*.spec.{ts,tsx,js,jsx}"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/coverage/**"
  - "**/*.min.js"
  - "**/*.d.ts"
  - "**/playwright-report/**"
  - "**/.turbo/**"

# Custom rules for healthcare domain
custom_rules:
  - name: "patient_data_validation"
    description: "Ensure patient data is properly validated"
    pattern: "patient|paciente|cpf|rg|sus"
    severity: "high"

  - name: "medical_data_encryption"
    description: "Check for proper encryption of medical data"
    pattern: "medical|medico|exame|diagnostico|prescription|receita"
    severity: "high"

  - name: "audit_logging"
    description: "Ensure audit trails for sensitive operations"
    pattern: "delete|update|create.*patient|create.*medical"
    severity: "medium"

  - name: "error_handling"
    description: "Proper error handling without data leakage"
    pattern: "try.*catch|throw.*Error"
    severity: "medium"

# Integration settings
integrations:
  github:
    auto_comment: true
    auto_approve_minor: false
    block_on_security_issues: true

  slack:
    enabled: false

  teams:
    enabled: false

# Notification settings
notifications:
  on_high_severity: true
  on_security_issues: true
  on_compliance_violations: true
  summary_reports: true

# Learning and improvement
learning:
  feedback_enabled: true
  continuous_improvement: true
  team_patterns_learning: true
