// API endpoint: GET/PUT/DELETE /api/automated-protocol-optimization/protocol-versions/[id]
// Story 9.3: Automated protocol optimization - Individual protocol version operations
// Generated by: VoidBeast V4.0
var __awaiter =
  (this && this.__awaiter) ||
  ((thisArg, _arguments, P, generator) => {
    function adopt(value) {
      return value instanceof P
        ? value
        : new P((resolve) => {
            resolve(value);
          });
    }
    return new (P || (P = Promise))((resolve, reject) => {
      function fulfilled(value) {
        try {
          step(generator.next(value));
        } catch (e) {
          reject(e);
        }
      }
      function rejected(value) {
        try {
          step(generator.throw(value));
        } catch (e) {
          reject(e);
        }
      }
      function step(result) {
        result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected);
      }
      step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
  });
var __generator =
  (this && this.__generator) ||
  ((thisArg, body) => {
    var _ = {
        label: 0,
        sent: () => {
          if (t[0] & 1) throw t[1];
          return t[1];
        },
        trys: [],
        ops: [],
      },
      f,
      y,
      t,
      g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return (
      (g.next = verb(0)),
      (g.throw = verb(1)),
      (g.return = verb(2)),
      typeof Symbol === "function" &&
        (g[Symbol.iterator] = function () {
          return this;
        }),
      g
    );
    function verb(n) {
      return (v) => step([n, v]);
    }
    function step(op) {
      if (f) throw new TypeError("Generator is already executing.");
      while ((g && ((g = 0), op[0] && (_ = 0)), _))
        try {
          if (
            ((f = 1),
            y &&
              (t =
                op[0] & 2
                  ? y.return
                  : op[0]
                    ? y.throw || ((t = y.return) && t.call(y), 0)
                    : y.next) &&
              !(t = t.call(y, op[1])).done)
          )
            return t;
          if (((y = 0), t)) op = [op[0] & 2, t.value];
          switch (op[0]) {
            case 0:
            case 1:
              t = op;
              break;
            case 4:
              _.label++;
              return { value: op[1], done: false };
            case 5:
              _.label++;
              y = op[1];
              op = [0];
              continue;
            case 7:
              op = _.ops.pop();
              _.trys.pop();
              continue;
            default:
              if (
                !((t = _.trys), (t = t.length > 0 && t[t.length - 1])) &&
                (op[0] === 6 || op[0] === 2)
              ) {
                _ = 0;
                continue;
              }
              if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) {
                _.label = op[1];
                break;
              }
              if (op[0] === 6 && _.label < t[1]) {
                _.label = t[1];
                t = op;
                break;
              }
              if (t && _.label < t[2]) {
                _.label = t[2];
                _.ops.push(op);
                break;
              }
              if (t[2]) _.ops.pop();
              _.trys.pop();
              continue;
          }
          op = body.call(thisArg, _);
        } catch (e) {
          op = [6, e];
          y = 0;
        } finally {
          f = t = 0;
        }
      if (op[0] & 5) throw op[1];
      return { value: op[0] ? op[1] : void 0, done: true };
    }
  });
Object.defineProperty(exports, "__esModule", { value: true });
exports.GET = GET;
exports.PUT = PUT;
exports.DELETE = DELETE;
var server_1 = require("next/server");
var automated_protocol_optimization_1 = require("../../../../lib/services/automated-protocol-optimization");
var automated_protocol_optimization_2 = require("../../../../lib/validations/automated-protocol-optimization");
var service = new automated_protocol_optimization_1.AutomatedProtocolOptimizationService();
// GET: Fetch single protocol version by ID
function GET(_request_1, _a) {
  return __awaiter(this, arguments, void 0, function (_request, _b) {
    var id, protocolVersion, error_1;
    var params = _b.params;
    return __generator(this, (_c) => {
      switch (_c.label) {
        case 0:
          _c.trys.push([0, 2, undefined, 3]);
          id = params.id;
          if (!id) {
            return [
              2 /*return*/,
              server_1.NextResponse.json(
                { success: false, error: "Protocol version ID is required" },
                { status: 400 },
              ),
            ];
          }
          return [4 /*yield*/, service.getProtocolVersionById(id)];
        case 1:
          protocolVersion = _c.sent();
          if (!protocolVersion) {
            return [
              2 /*return*/,
              server_1.NextResponse.json(
                { success: false, error: "Protocol version not found" },
                { status: 404 },
              ),
            ];
          }
          return [
            2 /*return*/,
            server_1.NextResponse.json({
              success: true,
              data: protocolVersion,
            }),
          ];
        case 2:
          error_1 = _c.sent();
          console.error("Error fetching protocol version:", error_1);
          return [
            2 /*return*/,
            server_1.NextResponse.json(
              {
                success: false,
                error: "Failed to fetch protocol version",
                details: error_1 instanceof Error ? error_1.message : "Unknown error",
              },
              { status: 500 },
            ),
          ];
        case 3:
          return [2 /*return*/];
      }
    });
  });
}
// PUT: Update protocol version
function PUT(_request_1, _a) {
  return __awaiter(this, arguments, void 0, function (request, _b) {
    var id, body, validation, updatedProtocolVersion, error_2;
    var params = _b.params;
    return __generator(this, (_c) => {
      switch (_c.label) {
        case 0:
          _c.trys.push([0, 3, undefined, 4]);
          id = params.id;
          return [4 /*yield*/, request.json()];
        case 1:
          body = _c.sent();
          if (!id) {
            return [
              2 /*return*/,
              server_1.NextResponse.json(
                { success: false, error: "Protocol version ID is required" },
                { status: 400 },
              ),
            ];
          }
          validation =
            automated_protocol_optimization_2.updateProtocolVersionSchema.safeParse(body);
          if (!validation.success) {
            return [
              2 /*return*/,
              server_1.NextResponse.json(
                {
                  success: false,
                  error: "Validation failed",
                  details: validation.error.format(),
                },
                { status: 400 },
              ),
            ];
          }
          return [4 /*yield*/, service.updateProtocolVersion(id, validation.data)];
        case 2:
          updatedProtocolVersion = _c.sent();
          return [
            2 /*return*/,
            server_1.NextResponse.json({
              success: true,
              data: updatedProtocolVersion,
              message: "Protocol version updated successfully",
            }),
          ];
        case 3:
          error_2 = _c.sent();
          console.error("Error updating protocol version:", error_2);
          return [
            2 /*return*/,
            server_1.NextResponse.json(
              {
                success: false,
                error: "Failed to update protocol version",
                details: error_2 instanceof Error ? error_2.message : "Unknown error",
              },
              { status: 500 },
            ),
          ];
        case 4:
          return [2 /*return*/];
      }
    });
  });
}
// DELETE: Delete protocol version
function DELETE(_request_1, _a) {
  return __awaiter(this, arguments, void 0, function (_request, _b) {
    var id, error_3;
    var params = _b.params;
    return __generator(this, (_c) => {
      switch (_c.label) {
        case 0:
          _c.trys.push([0, 2, undefined, 3]);
          id = params.id;
          if (!id) {
            return [
              2 /*return*/,
              server_1.NextResponse.json(
                { success: false, error: "Protocol version ID is required" },
                { status: 400 },
              ),
            ];
          }
          return [4 /*yield*/, service.deleteProtocolVersion(id)];
        case 1:
          _c.sent();
          return [
            2 /*return*/,
            server_1.NextResponse.json({
              success: true,
              message: "Protocol version deleted successfully",
            }),
          ];
        case 2:
          error_3 = _c.sent();
          console.error("Error deleting protocol version:", error_3);
          return [
            2 /*return*/,
            server_1.NextResponse.json(
              {
                success: false,
                error: "Failed to delete protocol version",
                details: error_3 instanceof Error ? error_3.message : "Unknown error",
              },
              { status: 500 },
            ),
          ];
        case 3:
          return [2 /*return*/];
      }
    });
  });
}
