// API endpoint: POST /api/automated-protocol-optimization/analysis
// Story 9.3: Automated protocol optimization - Trigger optimization analysis
// Generated by: VoidBeast V4.0

import { NextRequest, NextResponse } from 'next/server';
import { AutomatedProtocolOptimizationService } from '../../../lib/services/automated-protocol-optimization';
import { z } from 'zod';

const service = new AutomatedProtocolOptimizationService();

const triggerAnalysisSchema = z.object({
  protocol_id: z.string().uuid('Protocol ID must be a valid UUID'),
});

// POST: Trigger optimization analysis for a protocol
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    // Validate request data
    const validation = triggerAnalysisSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { 
          success: false, 
          error: 'Validation failed',
          details: validation.error.format()
        },
        { status: 400 }
      );
    }

    const { protocol_id } = validation.data;

    const optimizationResult = await service.triggerOptimizationAnalysis(protocol_id);

    return NextResponse.json({
      success: true,
      data: optimizationResult,
      message: 'Optimization analysis completed successfully'
    });
  } catch (error) {
    console.error('Error triggering optimization analysis:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to trigger optimization analysis',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

// GET: Get optimization results
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const protocol_id = searchParams.get('protocol_id') || undefined;

    const optimizationQueue = await service.getOptimizationResults(protocol_id);

    return NextResponse.json({
      success: true,
      data: optimizationQueue,
    });
  } catch (error) {
    console.error('Error fetching optimization results:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to fetch optimization results',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}
