name: Deploy Database Changes

on:
  push:
    paths: 
      - 'supabase/migrations/**'
      - 'supabase/config.toml'
      - '.github/workflows/deploy-database.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  NODE_VERSION: '18'

jobs:
  deploy:
    name: Deploy Database Changes
    runs-on: ubuntu-latest
    
    environment: 
      name: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'bun'
        
    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Setup Supabase CLI
      run: |
        curl -fsSL https://packages.supabase.com/api/installer.sh | bash
        
    - name: Link Supabase project
      run: |
        supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
    - name: Deploy database migrations
      run: supabase db push
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Generate TypeScript types
      run: |
        bun run db:types
      env:
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        
    - name: Commit generated types if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add packages/database/src/types/supabase-generated.ts
        if ! git diff --staged --quiet; then
          git commit -m "chore: update database types [skip ci]"
          git push
        fi
        
    - name: Run database tests
      run: bun test packages/database
      
    - name: Notify on success
      if: success()
      run: |
        echo "✅ Database deployed successfully!"
        echo "🚀 Migration applied to ${{ github.event.inputs.environment || 'production' }}"
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Database deployment failed!"
        echo "🔍 Check the logs above for details"