# Integração CI/CD para OxLint Hierárquico

name: OxLint Hierarchical Quality Gates

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-hierarchical:
    name: OxLint Hierarchical Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [security, healthcare, api, web, ui]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Make scripts executable
        run: chmod +x ./scripts/oxlint-hierarchical.sh

      - name: Run OxLint for ${{ matrix.module }}
        run: ./scripts/oxlint-hierarchical.sh check ${{ matrix.module }}
        continue-on-error: ${{ matrix.module != 'security' && matrix.module != 'healthcare' }}

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: oxlint-results-${{ matrix.module }}
          path: |
            .oxlint_cache/
            *.log
          retention-days: 7

  lint-security-critical:
    name: Security Critical Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Make scripts executable
        run: chmod +x ./scripts/oxlint-hierarchical.sh

      - name: Security Package Lint (MUST PASS)
        run: ./scripts/oxlint-hierarchical.sh check security

      - name: Healthcare Package Lint (MUST PASS)
        run: ./scripts/oxlint-hierarchical.sh check healthcare

      - name: Fail if critical packages have errors
        run: |
          echo "✅ Critical packages passed OxLint checks"

  lint-fix-preview:
    name: OxLint Fix Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Make scripts executable
        run: chmod +x ./scripts/oxlint-hierarchical.sh

      - name: Run safe fixes
        run: ./scripts/oxlint-hierarchical.sh fix all

      - name: Check for changes
        id: changes
        run: |
          if [[ -n $(git diff --name-only) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Files that would be changed by OxLint fixes:"
            git diff --name-only
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No files would be changed by OxLint fixes"
          fi

      - name: Create fix preview comment
        if: steps.changes.outputs.changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('OxLint Fix Preview')
            );

            const body = `## 🔧 OxLint Fix Preview

            OxLint found issues that can be automatically fixed. Run the following to apply fixes:

            \`\`\`bash
            # Safe fixes only
            ./scripts/oxlint-hierarchical.sh fix all

            # Safe fixes + suggestions (review changes)
            ./scripts/oxlint-hierarchical.sh fix-all all
            \`\`\`

            Files that would be changed:
            \`\`\`
            ${process.env.GITHUB_STEP_SUMMARY}
            \`\`\`
            `;

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }

  performance-check:
    name: OxLint Performance Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Make scripts executable
        run: chmod +x ./scripts/oxlint-hierarchical.sh

      - name: Benchmark OxLint Performance
        run: |
          echo "🚀 Benchmarking OxLint Hierarchical Performance..."

          # Time each module
          echo "## Performance Results" >> performance.md
          echo "" >> performance.md

          for module in security healthcare api web ui; do
            echo "Timing $module..."
            start_time=$(date +%s.%N)
            ./scripts/oxlint-hierarchical.sh check $module > /dev/null 2>&1 || true
            end_time=$(date +%s.%N)
            duration=$(echo "$end_time - $start_time" | bc)
            echo "- **$module**: ${duration}s" >> performance.md
          done

          # Time all modules
          echo "Timing all modules..."
          start_time=$(date +%s.%N)
          ./scripts/oxlint-hierarchical.sh check all > /dev/null 2>&1 || true
          end_time=$(date +%s.%N)
          duration=$(echo "$end_time - $start_time" | bc)
          echo "- **Total (all modules)**: ${duration}s" >> performance.md

          cat performance.md

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        with:
          name: oxlint-performance
          path: performance.md
          retention-days: 30
